-- =============================================================================
-- Finsoft ERP (Basic edition) — 92-lookups.sql
-- GENERATED from the former CHECK (column IN (...)) lists. Do not edit by hand:
-- change a value list here only by inserting/updating rows in "Lookups"."Lookups".
--
-- 1. every value of every list -> "Lookups"."Lookups"
-- 2. which column uses which list -> "Lookups"."LookupColumns"
-- 3. the generic validation trigger on every table that has a lookup column
-- =============================================================================

INSERT INTO "Lookups"."Lookups" ("lookupType", code, label, tone, "sortOrder", "isSystem", "parentCodes") VALUES
  ('AccountKind', 'HEADER', 'Header', 'neutral', 1, true, NULL),
  ('AccountKind', 'GROUP', 'Group', 'neutral', 2, true, NULL),
  ('AccountKind', 'POSTABLE', 'Postable', 'neutral', 3, true, NULL),
  ('AccountSubType', 'CASH', 'Cash', 'neutral', 1, true, ARRAY['1']),
  ('AccountSubType', 'BANK', 'Bank', 'neutral', 2, true, ARRAY['1']),
  ('AccountSubType', 'RECEIVABLE', 'Receivable', 'neutral', 3, true, ARRAY['1']),
  ('AccountSubType', 'INVENTORY', 'Inventory', 'neutral', 4, true, ARRAY['1']),
  ('AccountSubType', 'PREPAYMENT', 'Prepayment', 'neutral', 5, true, ARRAY['1']),
  ('AccountSubType', 'FIXED_ASSET', 'Fixed asset', 'neutral', 6, true, ARRAY['1']),
  ('AccountSubType', 'DEPOSIT', 'Deposit', 'neutral', 7, true, ARRAY['1']),
  ('AccountSubType', 'PAYABLE', 'Payable', 'neutral', 8, true, ARRAY['2']),
  ('AccountSubType', 'ACCRUAL', 'Accrual', 'neutral', 9, true, ARRAY['2']),
  ('AccountSubType', 'TAX', 'Tax', 'neutral', 10, true, ARRAY['2']),
  ('AccountSubType', 'STATUTORY', 'Statutory', 'neutral', 11, true, ARRAY['2']),
  ('AccountSubType', 'BORROWING', 'Borrowing', 'neutral', 12, true, ARRAY['2']),
  ('AccountSubType', 'CAPITAL', 'Capital', 'neutral', 13, true, ARRAY['3']),
  ('AccountSubType', 'RESERVE', 'Reserve', 'neutral', 14, true, ARRAY['3']),
  ('AccountSubType', 'DRAWINGS', 'Drawings', 'neutral', 15, true, ARRAY['3']),
  ('AccountSubType', 'SALES', 'Sales', 'neutral', 16, true, ARRAY['4']),
  ('AccountSubType', 'OTHER_INCOME', 'Other income', 'neutral', 17, true, ARRAY['4']),
  ('AccountSubType', 'FINANCE_INCOME', 'Finance income', 'neutral', 18, true, ARRAY['4']),
  ('AccountSubType', 'COST_OF_SALES', 'Cost of sales', 'neutral', 19, true, ARRAY['5']),
  ('AccountSubType', 'EMPLOYEE_COST', 'Employee cost', 'neutral', 20, true, ARRAY['5']),
  ('AccountSubType', 'PREMISES', 'Premises', 'neutral', 21, true, ARRAY['5']),
  ('AccountSubType', 'DEPRECIATION', 'Depreciation', 'neutral', 22, true, ARRAY['5']),
  ('AccountSubType', 'GENERAL_EXPENSE', 'General expense', 'neutral', 23, true, ARRAY['5']),
  ('AccountSubType', 'FINANCE_COST', 'Finance cost', 'neutral', 24, true, ARRAY['5']),
  ('AccountSubType', 'TAXATION', 'Taxation', 'neutral', 25, true, ARRAY['5']),
  ('AccountType', 'CURRENT', 'Current', 'neutral', 1, true, NULL),
  ('AccountType', 'SAVINGS_PLS', 'Savings pls', 'neutral', 2, true, NULL),
  ('AccountType', 'RUNNING_FINANCE', 'Running finance', 'neutral', 3, true, NULL),
  ('AccountType', 'FOREIGN_CURRENCY', 'Foreign currency', 'neutral', 4, true, NULL),
  ('ActiveInactiveStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('ActiveInactiveStatus', 'INACTIVE', 'Inactive', 'neutral', 2, true, NULL),
  ('AttachmentPurpose', 'DOCUMENT', 'Document', 'neutral', 1, true, NULL),
  ('AttachmentPurpose', 'RECEIPT', 'Receipt', 'neutral', 2, true, NULL),
  ('AttachmentPurpose', 'LOGO', 'Logo', 'neutral', 3, true, NULL),
  ('AttachmentPurpose', 'AVATAR', 'Avatar', 'neutral', 4, true, NULL),
  ('AttachmentPurpose', 'IMPORT_FILE', 'Import file', 'neutral', 5, true, NULL),
  ('AttachmentPurpose', 'REPORT_OUTPUT', 'Report output', 'neutral', 6, true, NULL),
  ('AttachmentPurpose', 'DATA_EXPORT', 'Data export', 'neutral', 7, true, NULL),
  ('AttachmentPurpose', 'OTHER', 'Other', 'neutral', 8, true, NULL),
  ('AuditTrailEntryAction', 'INSERT', 'Insert', 'neutral', 1, true, NULL),
  ('AuditTrailEntryAction', 'UPDATE', 'Update', 'neutral', 2, true, NULL),
  ('AuditTrailEntryAction', 'DELETE', 'Delete', 'neutral', 3, true, NULL),
  ('AuditTrailEntryAction', 'LOGIN', 'Login', 'neutral', 4, true, NULL),
  ('AuditTrailEntryAction', 'LOGOUT', 'Logout', 'neutral', 5, true, NULL),
  ('AuditTrailEntryAction', 'LOGIN_FAILED', 'Login failed', 'neutral', 6, true, NULL),
  ('AuditTrailEntryAction', 'PASSWORD_RESET', 'Password reset', 'neutral', 7, true, NULL),
  ('AuditTrailEntryAction', 'MFA_RESET', 'MFA reset', 'neutral', 8, true, NULL),
  ('AuditTrailEntryAction', 'SESSION_REVOKED', 'Session revoked', 'neutral', 9, true, NULL),
  ('AuditTrailEntryAction', 'POST', 'Post', 'neutral', 10, true, NULL),
  ('AuditTrailEntryAction', 'APPROVE', 'Approve', 'neutral', 11, true, NULL),
  ('AuditTrailEntryAction', 'REJECT', 'Reject', 'neutral', 12, true, NULL),
  ('AuditTrailEntryAction', 'VOID', 'Void', 'danger', 13, true, NULL),
  ('AuditTrailEntryAction', 'REVERSE', 'Reverse', 'neutral', 14, true, NULL),
  ('AuditTrailEntryAction', 'PERMISSION', 'Permission', 'neutral', 15, true, NULL),
  ('AuditTrailEntryAction', 'EXPORT', 'Export', 'neutral', 16, true, NULL),
  ('AuditTrailEntryModule', 'AUTH', 'Auth', 'neutral', 1, true, NULL),
  ('AuditTrailEntryModule', 'SETTINGS', 'Settings', 'neutral', 2, true, NULL),
  ('AuditTrailEntryModule', 'USERS', 'Users', 'neutral', 3, true, NULL),
  ('AuditTrailEntryModule', 'VOUCHERS', 'Vouchers', 'neutral', 4, true, NULL),
  ('AuditTrailEntryModule', 'ACCOUNTING', 'Accounting', 'neutral', 5, true, NULL),
  ('AuditTrailEntryModule', 'BANKING', 'Banking', 'neutral', 6, true, NULL),
  ('AuditTrailEntryModule', 'CASH', 'Cash', 'neutral', 7, true, NULL),
  ('AuditTrailEntryModule', 'SALES', 'Sales', 'neutral', 8, true, NULL),
  ('AuditTrailEntryModule', 'RECEIVABLES', 'Receivables', 'neutral', 9, true, NULL),
  ('AuditTrailEntryModule', 'PURCHASES', 'Purchases', 'neutral', 10, true, NULL),
  ('AuditTrailEntryModule', 'PAYABLES', 'Payables', 'neutral', 11, true, NULL),
  ('AuditTrailEntryModule', 'INVENTORY', 'Inventory', 'neutral', 12, true, NULL),
  ('AuditTrailEntryModule', 'TAX', 'Tax', 'neutral', 13, true, NULL),
  ('AuditTrailEntryModule', 'REPORTS', 'Reports', 'neutral', 14, true, NULL),
  ('AuditTrailEntryModule', 'SYSTEM', 'System posting', 'neutral', 15, true, NULL),
  ('BankAccountPurpose', 'PRIMARY', 'Primary', 'neutral', 1, true, NULL),
  ('BankAccountPurpose', 'COLLECTIONS', 'Collections', 'neutral', 2, true, NULL),
  ('BankAccountPurpose', 'VENDOR_PAYMENTS', 'Vendor payments', 'neutral', 3, true, NULL),
  ('BankAccountPurpose', 'PAYROLL', 'Payroll', 'neutral', 4, true, NULL),
  ('BankAccountPurpose', 'RUNNING_FINANCE', 'Running finance', 'neutral', 5, true, NULL),
  ('BankAccountPurpose', 'GENERAL', 'General', 'neutral', 6, true, NULL),
  ('BankAccountStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('BankAccountStatus', 'DORMANT', 'Dormant', 'neutral', 2, true, NULL),
  ('BankAccountStatus', 'CLOSED', 'Closed', 'good', 3, true, NULL),
  ('BankTransactionCategory', 'CUSTOMER_RECEIPT', 'Customer receipt', 'neutral', 1, true, NULL),
  ('BankTransactionCategory', 'VENDOR_PAYMENT', 'Vendor payment', 'neutral', 2, true, NULL),
  ('BankTransactionCategory', 'BANK_CHARGES', 'Bank charges', 'neutral', 3, true, NULL),
  ('BankTransactionCategory', 'PROFIT_ON_DEPOSIT', 'Profit on deposit', 'neutral', 4, true, NULL),
  ('BankTransactionCategory', 'MARKUP_EXPENSE', 'Markup expense', 'neutral', 5, true, NULL),
  ('BankTransactionCategory', 'CASH_DEPOSIT', 'Cash deposit', 'neutral', 6, true, NULL),
  ('BankTransactionCategory', 'CASH_WITHDRAWAL', 'Cash withdrawal', 'neutral', 7, true, NULL),
  ('BankTransactionCategory', 'TRANSFER', 'Transfer', 'neutral', 8, true, NULL),
  ('BankTransactionCategory', 'PAYROLL', 'Payroll', 'neutral', 9, true, NULL),
  ('BankTransactionCategory', 'TAX_PAYMENT', 'Tax payment', 'neutral', 10, true, NULL),
  ('BankTransactionCategory', 'LOAN', 'Loan', 'neutral', 11, true, NULL),
  ('BankTransactionCategory', 'OTHER', 'Other', 'neutral', 12, true, NULL),
  ('BankTransactionPaymentMode', 'CASH', 'Cash', 'neutral', 1, true, NULL),
  ('BankTransactionPaymentMode', 'CARD', 'Card', 'neutral', 2, true, NULL),
  ('BankTransactionPaymentMode', 'IBFT', 'IBFT', 'neutral', 3, true, NULL),
  ('BankTransactionPaymentMode', 'RAAST', 'RAAST', 'neutral', 4, true, NULL),
  ('BankTransactionPaymentMode', 'BANK_TRANSFER', 'Bank transfer', 'neutral', 5, true, NULL),
  ('BankTransactionPaymentMode', 'DEBIT_CARD', 'Debit card', 'neutral', 6, true, NULL),
  ('BankTransactionPaymentMode', 'CHEQUE', 'Cheque', 'neutral', 7, true, NULL),
  ('BankTransactionPaymentMode', 'ATM', 'Atm', 'neutral', 8, true, NULL),
  ('BankTransactionPaymentMode', 'SYSTEM', 'System posting', 'neutral', 9, true, NULL),
  ('BankTransactionSource', 'VOUCHER', 'Voucher', 'neutral', 1, true, NULL),
  ('BankTransactionSource', 'STATEMENT_IMPORT', 'Statement import', 'neutral', 2, true, NULL),
  ('BankTransactionSource', 'MANUAL', 'Manual', 'neutral', 3, true, NULL),
  ('BankTransactionStatus', 'UNCATEGORISED', 'Uncategorised', 'neutral', 1, true, NULL),
  ('BankTransactionStatus', 'PENDING', 'Pending', 'warn', 2, true, NULL),
  ('BankTransactionStatus', 'UNPRESENTED', 'Unpresented', 'warn', 3, true, NULL),
  ('BankTransactionStatus', 'UNCLEARED', 'Uncleared', 'neutral', 4, true, NULL),
  ('BankTransactionStatus', 'CLEARED', 'Cleared', 'good', 5, true, NULL),
  ('BankTransactionStatus', 'RECONCILED', 'Reconciled', 'good', 6, true, NULL),
  ('BillStatus', 'AWAITING', 'Awaiting', 'warn', 1, true, NULL),
  ('BillStatus', 'PARTIALLY_BILLED', 'Partially billed', 'warn', 2, true, NULL),
  ('BillStatus', 'BILLED', 'Billed', 'neutral', 3, true, NULL),
  ('BillingCycle', 'MONTHLY', 'Monthly', 'neutral', 1, true, NULL),
  ('BillingCycle', 'ANNUAL', 'Annual', 'neutral', 2, true, NULL),
  ('CaptureMethod', 'MANUAL', 'Manual', 'neutral', 1, true, NULL),
  ('CaptureMethod', 'OCR', 'Ocr', 'neutral', 2, true, NULL),
  ('CashAccountKind', 'DRAWER', 'Drawer', 'neutral', 1, true, NULL),
  ('CashAccountKind', 'COUNTER', 'Counter', 'neutral', 2, true, NULL),
  ('CashAccountKind', 'PETTY', 'Petty', 'neutral', 3, true, NULL),
  ('CashAccountKind', 'IMPREST', 'Imprest', 'neutral', 4, true, NULL),
  ('CashBookEntryPaymentMode', 'CASH', 'Cash', 'neutral', 1, true, NULL),
  ('CashBookEntryPaymentMode', 'CARD', 'Card', 'neutral', 2, true, NULL),
  ('CashBookEntryPaymentMode', 'IBFT', 'IBFT', 'neutral', 3, true, NULL),
  ('CashBookEntryPaymentMode', 'RAAST', 'RAAST', 'neutral', 4, true, NULL),
  ('CashBookEntryPaymentMode', 'BANK_TRANSFER', 'Bank transfer', 'neutral', 5, true, NULL),
  ('CashBookEntryPaymentMode', 'DEBIT_CARD', 'Debit card', 'neutral', 6, true, NULL),
  ('CashBookEntryPaymentMode', 'CHEQUE', 'Cheque', 'neutral', 7, true, NULL),
  ('CashCategoryDirection', 'IN', 'In', 'neutral', 1, true, NULL),
  ('CashCategoryDirection', 'OUT', 'Out', 'neutral', 2, true, NULL),
  ('CashCategoryDirection', 'TRANSFER', 'Transfer', 'neutral', 3, true, NULL),
  ('CashCategoryVoucherType', 'CRV', 'CRV', 'neutral', 1, true, NULL),
  ('CashCategoryVoucherType', 'CPV', 'CPV', 'neutral', 2, true, NULL),
  ('CashCategoryVoucherType', 'BRV', 'BRV', 'neutral', 3, true, NULL),
  ('CashCategoryVoucherType', 'BPV', 'BPV', 'neutral', 4, true, NULL),
  ('CashCategoryVoucherType', 'JV', 'JV', 'neutral', 5, true, NULL),
  ('CashCategoryVoucherType', 'CON', 'Contra', 'neutral', 6, true, NULL),
  ('CashDayCloseStatus', 'COUNTED', 'Counted', 'neutral', 1, true, NULL),
  ('CashDayCloseStatus', 'LOCKED', 'Locked', 'danger', 2, true, NULL),
  ('CashDayCloseStatus', 'REOPENED', 'Reopened', 'neutral', 3, true, NULL),
  ('ChartOfAccountsTemplateStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('ChartOfAccountsTemplateStatus', 'PUBLISHED', 'Published', 'good', 2, true, NULL),
  ('ChartOfAccountsTemplateStatus', 'DEFAULT', 'Default', 'good', 3, true, NULL),
  ('ChartOfAccountsTemplateStatus', 'RETIRED', 'Retired', 'danger', 4, true, NULL),
  ('ChequeBounceReason', 'INSUFFICIENT_FUNDS', 'Insufficient funds', 'neutral', 1, true, NULL),
  ('ChequeBounceReason', 'SIGNATURE_MISMATCH', 'Signature mismatch', 'neutral', 2, true, NULL),
  ('ChequeBounceReason', 'PAYMENT_STOPPED', 'Payment stopped', 'neutral', 3, true, NULL),
  ('ChequeBounceReason', 'ACCOUNT_CLOSED', 'Account closed', 'neutral', 4, true, NULL),
  ('ChequeBounceReason', 'STALE_OR_POSTDATED', 'Stale or postdated', 'neutral', 5, true, NULL),
  ('ChequeBounceReason', 'OTHER', 'Other', 'neutral', 6, true, NULL),
  ('ChequeStatus', 'IN_HAND', 'In hand', 'warn', 1, true, ARRAY['RECEIVED']),
  ('ChequeStatus', 'DEPOSITED', 'Deposited', 'info', 2, true, ARRAY['RECEIVED']),
  ('ChequeStatus', 'CLEARED', 'Cleared', 'good', 3, true, ARRAY['RECEIVED', 'ISSUED']),
  ('ChequeStatus', 'BOUNCED', 'Bounced', 'danger', 4, true, ARRAY['RECEIVED', 'ISSUED']),
  ('ChequeStatus', 'ISSUED', 'Issued', 'info', 5, true, ARRAY['ISSUED']),
  ('ChequeStatus', 'PRESENTED', 'Presented', 'info', 6, true, ARRAY['ISSUED']),
  ('ChequeStatus', 'STOPPED', 'Stopped', 'neutral', 7, true, ARRAY['ISSUED']),
  ('ChequeStatus', 'CANCELLED', 'Cancelled', 'danger', 8, true, ARRAY['RECEIVED', 'ISSUED']),
  ('ChequeStatus', 'REPLACED', 'Replaced', 'neutral', 9, true, ARRAY['RECEIVED', 'ISSUED']),
  ('ClientType', 'WEB', 'Web', 'neutral', 1, true, NULL),
  ('ClientType', 'IOS_APP', 'Ios app', 'neutral', 2, true, NULL),
  ('ClientType', 'ANDROID_APP', 'Android app', 'neutral', 3, true, NULL),
  ('ClientType', 'API', 'API', 'neutral', 4, true, NULL),
  ('CompanySettingAtlStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('CompanySettingAtlStatus', 'INACTIVE', 'Inactive', 'neutral', 2, true, NULL),
  ('CompanySettingAtlStatus', 'UNKNOWN', 'Unknown', 'neutral', 3, true, NULL),
  ('CompanySettingIndustry', 'TRADING_DISTRIBUTION', 'Trading distribution', 'neutral', 1, true, NULL),
  ('CompanySettingIndustry', 'MANUFACTURING', 'Manufacturing', 'neutral', 2, true, NULL),
  ('CompanySettingIndustry', 'SERVICES', 'Services', 'neutral', 3, true, NULL),
  ('CompanySettingIndustry', 'RETAIL', 'Retail', 'neutral', 4, true, NULL),
  ('CompanySettingIndustry', 'CONSTRUCTION', 'Construction', 'neutral', 5, true, NULL),
  ('CompanySettingIndustry', 'TEXTILES', 'Textiles', 'neutral', 6, true, NULL),
  ('CompanySettingIndustry', 'PHARMACEUTICALS', 'Pharmaceuticals', 'neutral', 7, true, NULL),
  ('CompanySettingIndustry', 'NGO', 'NGO', 'neutral', 8, true, NULL),
  ('ContactRole', 'OWNER', 'Owner', 'neutral', 1, true, NULL),
  ('ContactRole', 'BILLING', 'Billing', 'neutral', 2, true, NULL),
  ('ContactRole', 'TECHNICAL', 'Technical', 'neutral', 3, true, NULL),
  ('ContactRole', 'OTHER', 'Other', 'neutral', 4, true, NULL),
  ('CreditLimitAction', 'BLOCK_OVERRIDE', 'Block override', 'neutral', 1, true, NULL),
  ('CreditLimitAction', 'WARN', 'Warn', 'neutral', 2, true, NULL),
  ('CreditLimitAction', 'ALLOW', 'Allow', 'neutral', 3, true, NULL),
  ('CreditNoteReason', 'DAMAGED', 'Damaged', 'danger', 1, true, NULL),
  ('CreditNoteReason', 'SALES_RETURN', 'Sales return', 'neutral', 2, true, NULL),
  ('CreditNoteReason', 'RATE_DIFFERENCE', 'Rate difference', 'neutral', 3, true, NULL),
  ('CreditNoteReason', 'SHORT_SUPPLY', 'Short supply', 'neutral', 4, true, NULL),
  ('CreditNoteReason', 'OTHER', 'Other', 'neutral', 5, true, NULL),
  ('CreditNoteStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('CreditNoteStatus', 'PENDING_APPROVAL', 'Pending approval', 'warn', 2, true, NULL),
  ('CreditNoteStatus', 'OPEN', 'Open', 'good', 3, true, NULL),
  ('CreditNoteStatus', 'APPLIED', 'Applied', 'good', 4, true, NULL),
  ('CreditNoteStatus', 'CANCELLED', 'Cancelled', 'danger', 5, true, NULL),
  ('CreditNoteTreatment', 'APPLY_TO_INVOICE', 'Apply to invoice', 'neutral', 1, true, NULL),
  ('CreditNoteTreatment', 'KEEP_AS_CREDIT', 'Keep as credit', 'neutral', 2, true, NULL),
  ('CreditNoteTreatment', 'REFUND', 'Refund', 'neutral', 3, true, NULL),
  ('CustomerAtlStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('CustomerAtlStatus', 'NOT_ON_ATL', 'Not on ATL', 'neutral', 2, true, NULL),
  ('CustomerHoldReason', 'OVER_LIMIT', 'Over limit', 'neutral', 1, true, NULL),
  ('CustomerHoldReason', 'OVERDUE', 'Overdue', 'danger', 2, true, NULL),
  ('CustomerHoldReason', 'BOUNCED_CHEQUE', 'Bounced cheque', 'neutral', 3, true, NULL),
  ('CustomerHoldReason', 'MANUAL', 'Manual', 'neutral', 4, true, NULL),
  ('CustomerPaymentTerms', 'NET_15', 'Net 15', 'neutral', 1, true, NULL),
  ('CustomerPaymentTerms', 'NET_30', 'Net 30', 'neutral', 2, true, NULL),
  ('CustomerPaymentTerms', 'NET_45', 'Net 45', 'neutral', 3, true, NULL),
  ('CustomerPaymentTerms', 'NET_60', 'Net 60', 'neutral', 4, true, NULL),
  ('CustomerPaymentTerms', 'DUE_ON_RECEIPT', 'Due on receipt', 'neutral', 5, true, NULL),
  ('CustomerPaymentTerms', 'ADVANCE_50', 'Advance 50', 'neutral', 6, true, NULL),
  ('CustomerPaymentTerms', 'ADVANCE', 'Advance', 'neutral', 7, true, NULL),
  ('CustomerPaymentTerms', 'COD', 'COD', 'neutral', 8, true, NULL),
  ('CustomerReceiptAllocationTargetType', 'INVOICE', 'Invoice', 'neutral', 1, true, NULL),
  ('CustomerReceiptAllocationTargetType', 'CREDIT_NOTE', 'Credit note', 'neutral', 2, true, NULL),
  ('CustomerReceiptAllocationTargetType', 'OPENING_BALANCE', 'Opening balance', 'neutral', 3, true, NULL),
  ('CustomerReceiptMethod', 'IBFT', 'IBFT', 'neutral', 1, true, NULL),
  ('CustomerReceiptMethod', 'CHEQUE', 'Cheque', 'neutral', 2, true, NULL),
  ('CustomerReceiptMethod', 'CASH', 'Cash', 'neutral', 3, true, NULL),
  ('CustomerReceiptMethod', 'RAAST', 'RAAST', 'neutral', 4, true, NULL),
  ('CustomerReceiptMethod', 'CARD', 'Card', 'neutral', 5, true, NULL),
  ('CustomerReceiptMethod', 'JAZZCASH', 'Jazzcash', 'neutral', 6, true, NULL),
  ('CustomerReceiptMethod', 'EASYPAISA', 'Easypaisa', 'neutral', 7, true, NULL),
  ('CustomerReceiptStatus', 'UNALLOCATED', 'Unallocated', 'neutral', 1, true, NULL),
  ('CustomerReceiptStatus', 'PARTLY_ALLOCATED', 'Partly allocated', 'warn', 2, true, NULL),
  ('CustomerReceiptStatus', 'ALLOCATED', 'Allocated', 'good', 3, true, NULL),
  ('CustomerReceiptStatus', 'BOUNCED', 'Bounced', 'danger', 4, true, NULL),
  ('CustomerReceiptStatus', 'VOID', 'Void', 'danger', 5, true, NULL),
  ('CustomerStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('CustomerStatus', 'ON_HOLD', 'On hold', 'warn', 2, true, NULL),
  ('CustomerStatus', 'DISPUTED', 'Disputed', 'danger', 3, true, NULL),
  ('CustomerStatus', 'INACTIVE', 'Inactive', 'neutral', 4, true, NULL),
  ('CustomerType', 'COMPANY', 'Company', 'neutral', 1, true, NULL),
  ('CustomerType', 'INDIVIDUAL', 'Individual', 'neutral', 2, true, NULL),
  ('CustomerType', 'GOVERNMENT', 'Government', 'neutral', 3, true, NULL),
  ('CustomerType', 'AOP', 'AOP', 'neutral', 4, true, NULL),
  ('DataResidency', 'PK_LAHORE', 'PK lahore', 'neutral', 1, true, NULL),
  ('DataResidency', 'AE_DUBAI', 'AE dubai', 'neutral', 2, true, NULL),
  ('DataScope', 'OWN', 'Own', 'neutral', 1, true, NULL),
  ('DataScope', 'BRANCH', 'Branch', 'neutral', 2, true, NULL),
  ('DataScope', 'ALL', 'All', 'neutral', 3, true, NULL),
  ('DateFormat', 'DD MMM YYYY', 'Dd mmm yyyy', 'neutral', 1, true, NULL),
  ('DateFormat', 'DD/MM/YYYY', 'Dd/mm/yyyy', 'neutral', 2, true, NULL),
  ('DateFormat', 'YYYY-MM-DD', 'Yyyy mm dd', 'neutral', 3, true, NULL),
  ('DebitNoteReason', 'PURCHASE_RETURN', 'Purchase return', 'neutral', 1, true, NULL),
  ('DebitNoteReason', 'PRICE_VARIANCE', 'Price variance', 'warn', 2, true, NULL),
  ('DebitNoteReason', 'SHORT_SUPPLY', 'Short supply', 'neutral', 3, true, NULL),
  ('DebitNoteReason', 'QUALITY_REJECTION', 'Quality rejection', 'neutral', 4, true, NULL),
  ('DebitNoteSettlement', 'ADJUST_AGAINST_BILL', 'Adjust against bill', 'neutral', 1, true, NULL),
  ('DebitNoteSettlement', 'REQUEST_REFUND', 'Request refund', 'neutral', 2, true, NULL),
  ('DebitNoteStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('DebitNoteStatus', 'OPEN', 'Open', 'good', 2, true, NULL),
  ('DebitNoteStatus', 'APPLIED', 'Applied', 'good', 3, true, NULL),
  ('DebitNoteStatus', 'REFUNDED', 'Refunded', 'good', 4, true, NULL),
  ('DebitNoteStatus', 'VOID', 'Void', 'danger', 5, true, NULL),
  ('DefaultLanguage', 'EN', 'EN', 'neutral', 1, true, NULL),
  ('DefaultLanguage', 'UR', 'UR', 'neutral', 2, true, NULL),
  ('DefaultResetPolicy', 'NEVER', 'Never', 'neutral', 1, true, NULL),
  ('DefaultResetPolicy', 'YEARLY', 'Yearly', 'neutral', 2, true, NULL),
  ('DefaultResetPolicy', 'MONTHLY', 'Monthly', 'neutral', 3, true, NULL),
  ('DefaultWhtSection', '153_1_A', '153 1 a', 'neutral', 1, true, NULL),
  ('DefaultWhtSection', '153_1_B', '153 1 b', 'neutral', 2, true, NULL),
  ('DefaultWhtSection', '153_1_C', '153 1 c', 'neutral', 3, true, NULL),
  ('DefaultWhtSection', 'EXEMPT', 'Exempt', 'neutral', 4, true, NULL),
  ('DeliverySlot', 'MORNING', 'Morning', 'neutral', 1, true, NULL),
  ('DeliverySlot', 'AFTERNOON', 'Afternoon', 'neutral', 2, true, NULL),
  ('DeliverySlot', 'EVENING', 'Evening', 'neutral', 3, true, NULL),
  ('DocumentFont', 'INTER', 'Inter', 'neutral', 1, true, NULL),
  ('DocumentFont', 'NOTO_NASTALIQ_URDU', 'Noto nastaliq urdu', 'neutral', 2, true, NULL),
  ('DocumentTypeModule', 'core', 'Core', 'neutral', 1, true, NULL),
  ('DocumentTypeModule', 'acc', 'ACC', 'neutral', 2, true, NULL),
  ('DocumentTypeModule', 'treasury', 'Treasury', 'neutral', 3, true, NULL),
  ('DocumentTypeModule', 'fa', 'FA', 'neutral', 4, true, NULL),
  ('DocumentTypeModule', 'tax', 'Tax', 'neutral', 5, true, NULL),
  ('DocumentTypeModule', 'sales', 'Sales', 'neutral', 6, true, NULL),
  ('DocumentTypeModule', 'purchase', 'Purchase', 'neutral', 7, true, NULL),
  ('DocumentTypeModule', 'inv', 'INV', 'neutral', 8, true, NULL),
  ('DocumentTypeModule', 'dist', 'DIST', 'neutral', 9, true, NULL),
  ('DocumentTypeModule', 'hr', 'HR', 'neutral', 10, true, NULL),
  ('DocumentTypeModule', 'payroll', 'Payroll', 'neutral', 11, true, NULL),
  ('DocumentTypeModule', 'ess', 'ESS', 'neutral', 12, true, NULL),
  ('DocumentTypeModule', 'rpt', 'Rpt', 'neutral', 13, true, NULL),
  ('DraftPostedCancelledStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('DraftPostedCancelledStatus', 'POSTED', 'Posted', 'good', 2, true, NULL),
  ('DraftPostedCancelledStatus', 'CANCELLED', 'Cancelled', 'danger', 3, true, NULL),
  ('DunningCasePaymentMethod', 'CARD', 'Card', 'neutral', 1, true, NULL),
  ('DunningCasePaymentMethod', 'JAZZCASH', 'Jazzcash', 'neutral', 2, true, NULL),
  ('DunningCasePaymentMethod', 'EASYPAISA', 'Easypaisa', 'neutral', 3, true, NULL),
  ('DunningCasePaymentMethod', 'RAAST', 'RAAST', 'neutral', 4, true, NULL),
  ('DunningCasePaymentMethod', 'BANK_TRANSFER', 'Bank transfer', 'neutral', 5, true, NULL),
  ('DunningCasePaymentMethod', 'DIRECT_DEBIT', 'Direct debit', 'neutral', 6, true, NULL),
  ('DunningCasePaymentMethod', 'INVOICE', 'Invoice', 'neutral', 7, true, NULL),
  ('EnUrLanguage', 'EN', 'EN', 'neutral', 1, true, NULL),
  ('EnUrLanguage', 'UR', 'UR', 'neutral', 2, true, NULL),
  ('EntryKind', 'CASH_IN', 'Cash in', 'neutral', 1, true, NULL),
  ('EntryKind', 'CASH_OUT', 'Cash out', 'neutral', 2, true, NULL),
  ('EntryKind', 'BANK_IN', 'Bank in', 'neutral', 3, true, NULL),
  ('EntryKind', 'BANK_OUT', 'Bank out', 'neutral', 4, true, NULL),
  ('EntryKind', 'CHEQUE_IN', 'Cheque in', 'neutral', 5, true, NULL),
  ('EntryKind', 'CHEQUE_OUT', 'Cheque out', 'neutral', 6, true, NULL),
  ('EntryKind', 'TRANSFER', 'Transfer', 'neutral', 7, true, NULL),
  ('FbrStatus', 'NOT_REQUIRED', 'Not required', 'neutral', 1, true, NULL),
  ('FbrStatus', 'PENDING', 'Pending', 'warn', 2, true, NULL),
  ('FbrStatus', 'POSTED', 'Posted', 'good', 3, true, NULL),
  ('FbrStatus', 'FAILED', 'Failed', 'danger', 4, true, NULL),
  ('FxRateSource', 'SBP_DAILY', 'Sbp daily', 'neutral', 1, true, NULL),
  ('FxRateSource', 'MANUAL', 'Manual', 'neutral', 2, true, NULL),
  ('GoodsReceivedNoteMatchStatus', 'MATCHED', 'Matched', 'good', 1, true, NULL),
  ('GoodsReceivedNoteMatchStatus', 'QTY_VARIANCE', 'Qty variance', 'warn', 2, true, NULL),
  ('GoodsReceivedNoteMatchStatus', 'TWO_WAY_BILL_AWAITED', 'Two way bill awaited', 'neutral', 3, true, NULL),
  ('GoodsReceivedNoteMatchStatus', 'OVER_RECEIPT', 'Over receipt', 'danger', 4, true, NULL),
  ('Inclusion', 'INCLUDED', 'Included', 'good', 1, true, NULL),
  ('Inclusion', 'ADDON', 'Addon', 'warn', 2, true, NULL),
  ('Inclusion', 'NOT_AVAILABLE', 'Not available', 'danger', 3, true, NULL),
  ('LegalStructure', 'PRIVATE_LIMITED', 'Private limited', 'neutral', 1, true, NULL),
  ('LegalStructure', 'PUBLIC_LIMITED', 'Public limited', 'neutral', 2, true, NULL),
  ('LegalStructure', 'AOP_PARTNERSHIP', 'AOP partnership', 'neutral', 3, true, NULL),
  ('LegalStructure', 'SOLE_PROPRIETOR', 'Sole proprietor', 'neutral', 4, true, NULL),
  ('LoginHours', 'ANY', 'Any', 'neutral', 1, true, NULL),
  ('LoginHours', 'BUSINESS', 'Business', 'neutral', 2, true, NULL),
  ('LoginHours', 'CUSTOM', 'Custom', 'neutral', 3, true, NULL),
  ('MfaType', 'TOTP', 'TOTP', 'neutral', 1, true, NULL),
  ('MfaType', 'WEBAUTHN', 'Webauthn', 'neutral', 2, true, NULL),
  ('MfaType', 'SMS', 'SMS', 'neutral', 3, true, NULL),
  ('ModuleKey', 'ACC', 'ACC', 'neutral', 1, true, NULL),
  ('ModuleKey', 'SAL', 'SAL', 'neutral', 2, true, NULL),
  ('ModuleKey', 'PUR', 'PUR', 'neutral', 3, true, NULL),
  ('ModuleKey', 'INV', 'INV', 'neutral', 4, true, NULL),
  ('ModuleKey', 'FA', 'FA', 'neutral', 5, true, NULL),
  ('ModuleKey', 'PAY', 'PAY', 'neutral', 6, true, NULL),
  ('ModuleKey', 'ATT', 'ATT', 'neutral', 7, true, NULL),
  ('ModuleKey', 'REC', 'REC', 'neutral', 8, true, NULL),
  ('ModuleKey', 'ESS', 'ESS', 'neutral', 9, true, NULL),
  ('ModuleKey', 'FBR', 'FBR', 'neutral', 10, true, NULL),
  ('ModuleKey', 'DIST', 'DIST', 'neutral', 11, true, NULL),
  ('ModuleKey', 'POS', 'POS', 'neutral', 12, true, NULL),
  ('MovementType', 'GRN', 'GRN', 'neutral', 1, true, NULL),
  ('MovementType', 'PURCHASE_RETURN', 'Purchase return', 'neutral', 2, true, NULL),
  ('MovementType', 'SALE', 'Sale', 'neutral', 3, true, NULL),
  ('MovementType', 'SALES_RETURN', 'Sales return', 'neutral', 4, true, NULL),
  ('MovementType', 'MANUAL_IN', 'Manual in', 'neutral', 5, true, NULL),
  ('MovementType', 'MANUAL_OUT', 'Manual out', 'neutral', 6, true, NULL),
  ('MovementType', 'TRANSFER_OUT', 'Transfer out', 'neutral', 7, true, NULL),
  ('MovementType', 'TRANSFER_IN', 'Transfer in', 'neutral', 8, true, NULL),
  ('MovementType', 'ADJUSTMENT', 'Adjustment', 'neutral', 9, true, NULL),
  ('MovementType', 'COUNT', 'Count', 'neutral', 10, true, NULL),
  ('MovementType', 'ASSEMBLY', 'Assembly', 'neutral', 11, true, NULL),
  ('MovementType', 'BREAKAGE', 'Breakage', 'neutral', 12, true, NULL),
  ('MovementType', 'GIFT', 'Gift', 'neutral', 13, true, NULL),
  ('MovementType', 'SAMPLE', 'Sample', 'neutral', 14, true, NULL),
  ('MovementType', 'INTERNAL_USE', 'Internal use', 'neutral', 15, true, NULL),
  ('MovementType', 'OPENING', 'Opening', 'neutral', 16, true, NULL),
  ('MovementType', 'WRITE_OFF', 'Write off', 'neutral', 17, true, NULL),
  ('Nature', 'DR', 'DR', 'neutral', 1, true, NULL),
  ('Nature', 'CR', 'CR', 'neutral', 2, true, NULL),
  ('NormalBalance', 'DR', 'DR', 'neutral', 1, true, NULL),
  ('NormalBalance', 'CR', 'CR', 'neutral', 2, true, NULL),
  ('NotificationCategory', 'APPROVALS', 'Approvals', 'neutral', 1, true, NULL),
  ('NotificationCategory', 'FINANCE', 'Finance', 'neutral', 2, true, NULL),
  ('NotificationCategory', 'HR', 'HR', 'neutral', 3, true, NULL),
  ('NotificationCategory', 'SYSTEM', 'System posting', 'neutral', 4, true, NULL),
  ('NotificationSeverity', 'INFO', 'Info', 'info', 1, true, NULL),
  ('NotificationSeverity', 'GOOD', 'Good', 'good', 2, true, NULL),
  ('NotificationSeverity', 'WARN', 'Warn', 'neutral', 3, true, NULL),
  ('NotificationSeverity', 'DANGER', 'Danger', 'neutral', 4, true, NULL),
  ('NumberFormat', 'WESTERN', 'Western', 'neutral', 1, true, NULL),
  ('NumberFormat', 'SOUTH_ASIAN', 'South asian', 'neutral', 2, true, NULL),
  ('OpenClosedLockedStatus', 'OPEN', 'Open', 'good', 1, true, NULL),
  ('OpenClosedLockedStatus', 'CLOSED', 'Closed', 'good', 2, true, NULL),
  ('OpenClosedLockedStatus', 'LOCKED', 'Locked', 'danger', 3, true, NULL),
  ('OpenClosedStatus', 'OPEN', 'Open', 'good', 1, true, NULL),
  ('OpenClosedStatus', 'CLOSED', 'Closed', 'good', 2, true, NULL),
  ('OpeningBalanceStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('OpeningBalanceStatus', 'POSTED', 'Posted', 'good', 2, true, NULL),
  ('PaperSize', 'A4', 'A4', 'neutral', 1, true, NULL),
  ('PaperSize', 'LETTER', 'Letter', 'neutral', 2, true, NULL),
  ('PartyKind', 'NONE', 'None', 'neutral', 1, true, NULL),
  ('PartyKind', 'CUSTOMER', 'Customer', 'neutral', 2, true, NULL),
  ('PartyKind', 'VENDOR', 'Vendor', 'neutral', 3, true, NULL),
  ('PartyKind', 'EMPLOYEE', 'Employee', 'neutral', 4, true, NULL),
  ('PartyKind', 'BANK', 'Bank', 'neutral', 5, true, NULL),
  ('PasswordResetChannel', 'EMAIL', 'Email', 'neutral', 1, true, NULL),
  ('PasswordResetChannel', 'WHATSAPP', 'Whatsapp', 'neutral', 2, true, NULL),
  ('PasswordResetChannel', 'SMS', 'SMS', 'neutral', 3, true, NULL),
  ('PasswordResetPurpose', 'RESET', 'Reset', 'neutral', 1, true, NULL),
  ('PasswordResetPurpose', 'INVITE', 'Invite', 'neutral', 2, true, NULL),
  ('PasswordResetPurpose', 'ADMIN_RESET', 'Admin reset', 'neutral', 3, true, NULL),
  ('PermissionAction', 'VIEW', 'View', 'neutral', 1, true, NULL),
  ('PermissionAction', 'CREATE', 'Create', 'neutral', 2, true, NULL),
  ('PermissionAction', 'EDIT', 'Edit', 'neutral', 3, true, NULL),
  ('PermissionAction', 'APPROVE', 'Approve', 'neutral', 4, true, NULL),
  ('PermissionAction', 'POST', 'Post', 'neutral', 5, true, NULL),
  ('PermissionAction', 'DELETE', 'Delete', 'neutral', 6, true, NULL),
  ('PermissionAction', 'EXPORT', 'Export', 'neutral', 7, true, NULL),
  ('PermissionModule', 'FINANCE', 'Finance', 'neutral', 1, true, NULL),
  ('PermissionModule', 'SALES_PURCHASES', 'Sales purchases', 'neutral', 2, true, NULL),
  ('PermissionModule', 'INVENTORY', 'Inventory', 'neutral', 3, true, NULL),
  ('PermissionModule', 'HR_PAYROLL', 'HR payroll', 'neutral', 4, true, NULL),
  ('PermissionModule', 'SYSTEM', 'System posting', 'neutral', 5, true, NULL),
  ('PlatformAuditLogResult', 'SUCCESS', 'Success', 'good', 1, true, NULL),
  ('PlatformAuditLogResult', 'FAILED', 'Failed', 'danger', 2, true, NULL),
  ('PlatformAuditLogResult', 'BLOCKED', 'Blocked', 'danger', 3, true, NULL),
  ('PlatformAuditLogResult', 'RECORDED', 'Recorded', 'neutral', 4, true, NULL),
  ('PlatformStaffMemberRole', 'SUPER_ADMIN', 'Super admin', 'neutral', 1, true, NULL),
  ('PlatformStaffMemberRole', 'SUPPORT_LEAD', 'Support lead', 'neutral', 2, true, NULL),
  ('PlatformStaffMemberRole', 'SUPPORT_AGENT', 'Support agent', 'neutral', 3, true, NULL),
  ('PlatformStaffMemberRole', 'BILLING', 'Billing', 'neutral', 4, true, NULL),
  ('PlatformStaffMemberRole', 'ENGINEER', 'Engineer', 'neutral', 5, true, NULL),
  ('PlatformStaffMemberStatus', 'INVITED', 'Invited', 'warn', 1, true, NULL),
  ('PlatformStaffMemberStatus', 'ACTIVE', 'Active', 'good', 2, true, NULL),
  ('PlatformStaffMemberStatus', 'SUSPENDED', 'Suspended', 'danger', 3, true, NULL),
  ('PlatformStaffMemberStatus', 'DISABLED', 'Disabled', 'danger', 4, true, NULL),
  ('PostingMode', 'DEPOSIT', 'Deposit', 'neutral', 1, true, NULL),
  ('PostingMode', 'HOLD_PDC', 'Hold PDC', 'neutral', 2, true, NULL),
  ('PostingMode', 'CLEAR_ON_DEPOSIT', 'Clear on deposit', 'neutral', 3, true, NULL),
  ('ProductBarcodeKind', 'PIECE', 'Piece', 'neutral', 1, true, NULL),
  ('ProductBarcodeKind', 'CARTON', 'Carton', 'neutral', 2, true, NULL),
  ('ProductBatchDisposition', 'SALEABLE', 'Saleable', 'good', 1, true, NULL),
  ('ProductBatchDisposition', 'PRIORITY', 'Priority', 'warn', 2, true, NULL),
  ('ProductBatchDisposition', 'QUARANTINE', 'Quarantine', 'danger', 3, true, NULL),
  ('ProductBatchDisposition', 'CLEARANCE', 'Clearance', 'warn', 4, true, NULL),
  ('ProductBatchDisposition', 'RETURN_TO_PRINCIPAL', 'Return to principal', 'neutral', 5, true, NULL),
  ('ProductBatchDisposition', 'WRITTEN_OFF', 'Written off', 'danger', 6, true, NULL),
  ('ProductStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('ProductStatus', 'DRAFT', 'Draft', 'neutral', 2, true, NULL),
  ('ProductStatus', 'INACTIVE', 'Inactive', 'neutral', 3, true, NULL),
  ('Province', 'PUNJAB', 'Punjab', 'neutral', 1, true, NULL),
  ('Province', 'SINDH', 'Sindh', 'neutral', 2, true, NULL),
  ('Province', 'KPK', 'KPK', 'neutral', 3, true, NULL),
  ('Province', 'ICT', 'ICT', 'neutral', 4, true, NULL),
  ('Province', 'BALOCHISTAN', 'Balochistan', 'neutral', 5, true, NULL),
  ('Province', 'GB', 'GB', 'neutral', 6, true, NULL),
  ('Province', 'AJK', 'AJK', 'neutral', 7, true, NULL),
  ('ProvincialTaxAuthority', 'PRA', 'PRA', 'neutral', 1, true, NULL),
  ('ProvincialTaxAuthority', 'SRB', 'SRB', 'neutral', 2, true, NULL),
  ('ProvincialTaxAuthority', 'KPRA', 'Kpra', 'neutral', 3, true, NULL),
  ('ProvincialTaxAuthority', 'BRA', 'Bra', 'neutral', 4, true, NULL),
  ('ProvincialTaxAuthority', 'ICT', 'ICT', 'neutral', 5, true, NULL),
  ('PurchaseOrderPaymentTerms', 'ADVANCE', 'Advance', 'neutral', 1, true, NULL),
  ('PurchaseOrderPaymentTerms', 'ON_RECEIPT', 'On receipt', 'neutral', 2, true, NULL),
  ('PurchaseOrderPaymentTerms', 'NET_7', 'Net 7', 'neutral', 3, true, NULL),
  ('PurchaseOrderPaymentTerms', 'NET_14', 'Net 14', 'neutral', 4, true, NULL),
  ('PurchaseOrderPaymentTerms', 'NET_15', 'Net 15', 'neutral', 5, true, NULL),
  ('PurchaseOrderPaymentTerms', 'NET_30', 'Net 30', 'neutral', 6, true, NULL),
  ('PurchaseOrderPaymentTerms', 'NET_45', 'Net 45', 'neutral', 7, true, NULL),
  ('PurchaseOrderPaymentTerms', 'NET_60', 'Net 60', 'neutral', 8, true, NULL),
  ('PurchaseOrderPaymentTerms', 'NET_90', 'Net 90', 'neutral', 9, true, NULL),
  ('PurchaseOrderStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('PurchaseOrderStatus', 'PENDING_L1', 'Pending L1', 'warn', 2, true, NULL),
  ('PurchaseOrderStatus', 'PENDING_L2', 'Pending L2', 'warn', 3, true, NULL),
  ('PurchaseOrderStatus', 'APPROVED', 'Approved', 'good', 4, true, NULL),
  ('PurchaseOrderStatus', 'PARTIALLY_RECEIVED', 'Partially received', 'warn', 5, true, NULL),
  ('PurchaseOrderStatus', 'RECEIVED', 'Received', 'good', 6, true, NULL),
  ('PurchaseOrderStatus', 'BILLED', 'Billed', 'neutral', 7, true, NULL),
  ('PurchaseOrderStatus', 'CANCELLED', 'Cancelled', 'danger', 8, true, NULL),
  ('QcStatus', 'PASSED', 'Passed', 'good', 1, true, NULL),
  ('QcStatus', 'PARTIAL_REJECT', 'Partial reject', 'warn', 2, true, NULL),
  ('QuotationStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('QuotationStatus', 'SENT', 'Sent', 'info', 2, true, NULL),
  ('QuotationStatus', 'ACCEPTED', 'Accepted', 'good', 3, true, NULL),
  ('QuotationStatus', 'EXPIRED', 'Expired', 'danger', 4, true, NULL),
  ('QuotationStatus', 'CONVERTED', 'Converted', 'good', 5, true, NULL),
  ('QuotationStatus', 'CANCELLED', 'Cancelled', 'danger', 6, true, NULL),
  ('RateBasis', 'PERCENT', 'Percent', 'neutral', 1, true, NULL),
  ('RateBasis', 'SLAB', 'Slab', 'neutral', 2, true, NULL),
  ('RateBasis', 'NONE', 'None', 'neutral', 3, true, NULL),
  ('ReceivedIssuedDirection', 'RECEIVED', 'Received', 'good', 1, true, NULL),
  ('ReceivedIssuedDirection', 'ISSUED', 'Issued', 'info', 2, true, NULL),
  ('RejectReason', 'DAMAGED_IN_TRANSIT', 'Damaged in transit', 'neutral', 1, true, NULL),
  ('RejectReason', 'SHORT_EXPIRY', 'Short expiry', 'neutral', 2, true, NULL),
  ('RejectReason', 'WRONG_ITEM', 'Wrong item', 'neutral', 3, true, NULL),
  ('RejectReason', 'FAILED_QC', 'Failed qc', 'neutral', 4, true, NULL),
  ('RejectReason', 'EXCESS_OVER_PO', 'Excess over PO', 'neutral', 5, true, NULL),
  ('ResetPolicy', 'NEVER', 'Never', 'neutral', 1, true, NULL),
  ('ResetPolicy', 'YEARLY', 'Yearly', 'neutral', 2, true, NULL),
  ('ResetPolicy', 'MONTHLY', 'Monthly', 'neutral', 3, true, NULL),
  ('Resolution', 'OPEN', 'Open', 'good', 1, true, NULL),
  ('Resolution', 'REPRESENTED', 'Represented', 'neutral', 2, true, NULL),
  ('Resolution', 'REPLACED', 'Replaced', 'neutral', 3, true, NULL),
  ('Resolution', 'RECOVERED', 'Recovered', 'neutral', 4, true, NULL),
  ('Resolution', 'WRITTEN_OFF', 'Written off', 'danger', 5, true, NULL),
  ('ReversalReason', 'INCORRECT_AMOUNT', 'Incorrect amount', 'neutral', 1, true, NULL),
  ('ReversalReason', 'WRONG_ACCOUNT', 'Wrong account', 'neutral', 2, true, NULL),
  ('ReversalReason', 'DUPLICATE', 'Duplicate', 'neutral', 3, true, NULL),
  ('ReversalReason', 'WRONG_PERIOD', 'Wrong period', 'neutral', 4, true, NULL),
  ('ReversalReason', 'OTHER', 'Other', 'neutral', 5, true, NULL),
  ('RevokeReason', 'SIGN_OUT', 'Sign out', 'neutral', 1, true, NULL),
  ('RevokeReason', 'USER_REVOKED', 'User revoked', 'neutral', 2, true, NULL),
  ('RevokeReason', 'ADMIN_REVOKED', 'Admin revoked', 'neutral', 3, true, NULL),
  ('RevokeReason', 'SUSPENDED', 'Suspended', 'danger', 4, true, NULL),
  ('RevokeReason', 'PASSWORD_CHANGED', 'Password changed', 'neutral', 5, true, NULL),
  ('RevokeReason', 'IDLE_TIMEOUT', 'Idle timeout', 'neutral', 6, true, NULL),
  ('RevokeReason', 'EXPIRED', 'Expired', 'danger', 7, true, NULL),
  ('RoleGroup', 'CONTROL', 'Control', 'neutral', 1, true, NULL),
  ('RoleGroup', 'REVENUE', 'Revenue', 'neutral', 2, true, NULL),
  ('RoleGroup', 'TAX', 'Tax', 'neutral', 3, true, NULL),
  ('RoleGroup', 'CASH_BANK', 'Cash bank', 'neutral', 4, true, NULL),
  ('RoleGroup', 'INVENTORY', 'Inventory', 'neutral', 5, true, NULL),
  ('RoleGroup', 'PURCHASE', 'Purchase', 'neutral', 6, true, NULL),
  ('RoleGroup', 'EQUITY', 'Equity', 'neutral', 7, true, NULL),
  ('RoleGroup', 'PAYROLL', 'Payroll', 'neutral', 8, true, NULL),
  ('RoleGroup', 'DISTRIBUTION', 'Distribution', 'neutral', 9, true, NULL),
  ('RoleGroup', 'ASSETS', 'Assets', 'neutral', 10, true, NULL),
  ('RoleGroup', 'OTHER', 'Other', 'neutral', 11, true, NULL),
  ('RoleTone', 'violet', 'Violet', 'neutral', 1, true, NULL),
  ('RoleTone', 'green', 'Green', 'neutral', 2, true, NULL),
  ('RoleTone', 'blue', 'Blue', 'neutral', 3, true, NULL),
  ('RoleTone', 'orange', 'Orange', 'neutral', 4, true, NULL),
  ('RoleTone', 'teal', 'Teal', 'neutral', 5, true, NULL),
  ('RoleTone', 'yellow', 'Yellow', 'neutral', 6, true, NULL),
  ('RoleTone', 'brown', 'Brown', 'neutral', 7, true, NULL),
  ('RoleTone', 'neutral', 'Neutral', 'neutral', 8, true, NULL),
  ('RoleTone', 'lime', 'Lime', 'neutral', 9, true, NULL),
  ('RoleTone', 'red', 'Red', 'neutral', 10, true, NULL),
  ('SaleType', 'REGULAR', 'Regular', 'neutral', 1, true, NULL),
  ('SaleType', 'WHOLESALE', 'Wholesale', 'neutral', 2, true, NULL),
  ('SaleType', 'RETAIL', 'Retail', 'neutral', 3, true, NULL),
  ('SaleType', 'DISTRIBUTOR', 'Distributor', 'neutral', 4, true, NULL),
  ('SalesInvoiceChannel', 'STANDARD', 'Standard', 'neutral', 1, true, NULL),
  ('SalesInvoiceChannel', 'COUNTER', 'Counter', 'neutral', 2, true, NULL),
  ('SalesInvoiceStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('SalesInvoiceStatus', 'POSTED', 'Posted', 'good', 2, true, NULL),
  ('SalesInvoiceStatus', 'PARTIALLY_PAID', 'Partially paid', 'warn', 3, true, NULL),
  ('SalesInvoiceStatus', 'PAID', 'Paid', 'good', 4, true, NULL),
  ('SalesInvoiceStatus', 'VOID', 'Void', 'danger', 5, true, NULL),
  ('SalesOrderStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('SalesOrderStatus', 'CONFIRMED', 'Confirmed', 'good', 2, true, NULL),
  ('SalesOrderStatus', 'PARTIALLY_DELIVERED', 'Partially delivered', 'warn', 3, true, NULL),
  ('SalesOrderStatus', 'TO_INVOICE', 'To invoice', 'neutral', 4, true, NULL),
  ('SalesOrderStatus', 'INVOICED', 'Invoiced', 'good', 5, true, NULL),
  ('SalesOrderStatus', 'ON_HOLD', 'On hold', 'warn', 6, true, NULL),
  ('SalesOrderStatus', 'CANCELLED', 'Cancelled', 'danger', 7, true, NULL),
  ('SalesTaxAuthority', 'FBR', 'FBR', 'neutral', 1, true, NULL),
  ('SalesTaxAuthority', 'PRA', 'PRA', 'neutral', 2, true, NULL),
  ('SalesTaxAuthority', 'SRB', 'SRB', 'neutral', 3, true, NULL),
  ('SalesTaxAuthority', 'KPRA', 'Kpra', 'neutral', 4, true, NULL),
  ('SalesTaxAuthority', 'BRA', 'Bra', 'neutral', 5, true, NULL),
  ('SalesTaxAuthority', 'ICT', 'ICT', 'neutral', 6, true, NULL),
  ('SalesTaxKind', 'STANDARD', 'Standard', 'neutral', 1, true, NULL),
  ('SalesTaxKind', 'ZERO_RATED', 'Zero rated', 'neutral', 2, true, NULL),
  ('SalesTaxKind', 'EXEMPT', 'Exempt', 'neutral', 3, true, NULL),
  ('SalesTaxKind', 'REDUCED', 'Reduced', 'neutral', 4, true, NULL),
  ('SalesTaxKind', 'FURTHER', 'Further', 'neutral', 5, true, NULL),
  ('SalesTaxReturnPeriod', 'MONTHLY', 'Monthly', 'neutral', 1, true, NULL),
  ('SalesTaxReturnPeriod', 'QUARTERLY', 'Quarterly', 'neutral', 2, true, NULL),
  ('SettingGroup', 'PROFILE', 'Profile', 'neutral', 1, true, NULL),
  ('SettingGroup', 'FINANCE', 'Finance', 'neutral', 2, true, NULL),
  ('SettingGroup', 'SALES', 'Sales', 'neutral', 3, true, NULL),
  ('SettingGroup', 'PURCHASE', 'Purchase', 'neutral', 4, true, NULL),
  ('SettingGroup', 'TAX', 'Tax', 'neutral', 5, true, NULL),
  ('SettingGroup', 'BRANDING', 'Branding', 'neutral', 6, true, NULL),
  ('SettingGroup', 'SECURITY', 'Security', 'neutral', 7, true, NULL),
  ('SettingGroup', 'NOTIFICATION', 'Notification', 'neutral', 8, true, NULL),
  ('SettingGroup', 'UI', 'Ui', 'neutral', 9, true, NULL),
  ('StartRoute', 'app/dashboard', 'App/dashboard', 'neutral', 1, true, NULL),
  ('StartRoute', 'app/today', 'App/today', 'neutral', 2, true, NULL),
  ('StartRoute', 'app/accounting/vouchers', 'App/accounting/vouchers', 'neutral', 3, true, NULL),
  ('StatementFormat', 'BANK_CSV', 'Bank CSV', 'neutral', 1, true, NULL),
  ('StatementFormat', 'EXCEL', 'Excel', 'neutral', 2, true, NULL),
  ('StatementFormat', 'MT940', 'MT940', 'neutral', 3, true, NULL),
  ('StatementFormat', 'CUSTOM', 'Custom', 'neutral', 4, true, NULL),
  ('StockAdjustmentStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('StockAdjustmentStatus', 'PENDING_APPROVAL', 'Pending approval', 'warn', 2, true, NULL),
  ('StockAdjustmentStatus', 'POSTED', 'Posted', 'good', 3, true, NULL),
  ('StockAdjustmentStatus', 'REJECTED', 'Rejected', 'danger', 4, true, NULL),
  ('StockAdjustmentStatus', 'CANCELLED', 'Cancelled', 'danger', 5, true, NULL),
  ('StockInOutEntryMode', 'IN', 'In', 'neutral', 1, true, NULL),
  ('StockInOutEntryMode', 'OUT', 'Out', 'neutral', 2, true, NULL),
  ('StockMovementReasonDirection', 'IN', 'In', 'neutral', 1, true, NULL),
  ('StockMovementReasonDirection', 'OUT', 'Out', 'neutral', 2, true, NULL),
  ('StockMovementReasonDirection', 'ADJ', 'Adjustment', 'neutral', 3, true, NULL),
  ('StockMovementReasonLedgerMovementType', 'MANUAL_IN', 'Manual in', 'neutral', 1, true, ARRAY['IN']),
  ('StockMovementReasonLedgerMovementType', 'MANUAL_OUT', 'Manual out', 'neutral', 2, true, ARRAY['OUT']),
  ('StockMovementReasonLedgerMovementType', 'OPENING', 'Opening', 'neutral', 3, true, ARRAY['IN']),
  ('StockMovementReasonLedgerMovementType', 'ADJUSTMENT', 'Adjustment', 'neutral', 4, true, ARRAY['ADJ']),
  ('StockMovementReasonLedgerMovementType', 'WRITE_OFF', 'Write off', 'neutral', 5, true, ARRAY['OUT', 'ADJ']),
  ('StockTransferStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('StockTransferStatus', 'POSTED', 'Posted', 'good', 2, true, NULL),
  ('StockTransferStatus', 'DISPATCHED', 'Dispatched', 'warn', 3, true, NULL),
  ('StockTransferStatus', 'IN_TRANSIT', 'In transit', 'warn', 4, true, NULL),
  ('StockTransferStatus', 'RECEIVED', 'Received', 'good', 5, true, NULL),
  ('StockTransferStatus', 'CANCELLED', 'Cancelled', 'danger', 6, true, NULL),
  ('SubscriptionPlanStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('SubscriptionPlanStatus', 'RETIRED', 'Retired', 'danger', 2, true, NULL),
  ('SubscriptionStatus', 'TRIAL', 'Trial', 'warn', 1, true, NULL),
  ('SubscriptionStatus', 'ACTIVE', 'Active', 'good', 2, true, NULL),
  ('SubscriptionStatus', 'PAST_DUE', 'Past due', 'warn', 3, true, NULL),
  ('SubscriptionStatus', 'SUSPENDED', 'Suspended', 'danger', 4, true, NULL),
  ('SubscriptionStatus', 'CANCELLED', 'Cancelled', 'danger', 5, true, NULL),
  ('SubscriptionStatus', 'EXPIRED', 'Expired', 'danger', 6, true, NULL),
  ('SystemKey', 'OWNER', 'Owner', 'neutral', 1, true, NULL),
  ('SystemKey', 'FINANCE_MANAGER', 'Finance manager', 'neutral', 2, true, NULL),
  ('SystemKey', 'ACCOUNTANT', 'Accountant', 'neutral', 3, true, NULL),
  ('SystemKey', 'HR_MANAGER', 'HR manager', 'neutral', 4, true, NULL),
  ('SystemKey', 'PAYROLL_OFFICER', 'Payroll officer', 'neutral', 5, true, NULL),
  ('SystemKey', 'SALES_EXECUTIVE', 'Sales executive', 'neutral', 6, true, NULL),
  ('SystemKey', 'STOREKEEPER', 'Storekeeper', 'neutral', 7, true, NULL),
  ('SystemKey', 'AUDITOR', 'Auditor', 'neutral', 8, true, NULL),
  ('TaxCodeAppliesTo', 'SALES', 'Sales', 'neutral', 1, true, NULL),
  ('TaxCodeAppliesTo', 'PURCHASES', 'Purchases', 'neutral', 2, true, NULL),
  ('TaxCodeAppliesTo', 'SALES_AND_PURCHASES', 'Sales and purchases', 'neutral', 3, true, NULL),
  ('TaxCodeAppliesTo', 'VENDOR_PAYMENTS', 'Vendor payments', 'neutral', 4, true, NULL),
  ('TaxCodeAppliesTo', 'CUSTOMER_RECEIPTS', 'Customer receipts', 'neutral', 5, true, NULL),
  ('TaxCodeAppliesTo', 'PAYROLL', 'Payroll', 'neutral', 6, true, NULL),
  ('TaxType', 'SALES_TAX', 'Sales tax', 'neutral', 1, true, NULL),
  ('TaxType', 'WITHHOLDING', 'Withholding', 'neutral', 2, true, NULL),
  ('TaxType', 'COLLECTION', 'Collection', 'neutral', 3, true, NULL),
  ('TenantIndustry', 'TRADING_DISTRIBUTION', 'Trading distribution', 'neutral', 1, true, NULL),
  ('TenantIndustry', 'MANUFACTURING', 'Manufacturing', 'neutral', 2, true, NULL),
  ('TenantIndustry', 'SERVICES', 'Services', 'neutral', 3, true, NULL),
  ('TenantIndustry', 'TEXTILES', 'Textiles', 'neutral', 4, true, NULL),
  ('TenantIndustry', 'PHARMACEUTICALS', 'Pharmaceuticals', 'neutral', 5, true, NULL),
  ('TenantIndustry', 'CONSTRUCTION', 'Construction', 'neutral', 6, true, NULL),
  ('TenantIndustry', 'NGO', 'NGO', 'neutral', 7, true, NULL),
  ('TenantModuleSource', 'PLAN', 'Plan', 'neutral', 1, true, NULL),
  ('TenantModuleSource', 'ADDON', 'Addon', 'warn', 2, true, NULL),
  ('TenantModuleSource', 'TRIAL', 'Trial', 'warn', 3, true, NULL),
  ('TenantModuleSource', 'OVERRIDE', 'Override', 'neutral', 4, true, NULL),
  ('TenantScope', 'ALL', 'All', 'neutral', 1, true, NULL),
  ('TenantScope', 'ASSIGNED', 'Assigned', 'neutral', 2, true, NULL),
  ('TenantStatus', 'PROVISIONING', 'Provisioning', 'warn', 1, true, NULL),
  ('TenantStatus', 'TRIAL', 'Trial', 'warn', 2, true, NULL),
  ('TenantStatus', 'ACTIVE', 'Active', 'good', 3, true, NULL),
  ('TenantStatus', 'PAST_DUE', 'Past due', 'warn', 4, true, NULL),
  ('TenantStatus', 'READ_ONLY', 'Read only', 'danger', 5, true, NULL),
  ('TenantStatus', 'SUSPENDED', 'Suspended', 'danger', 6, true, NULL),
  ('TenantStatus', 'CHURNED', 'Churned', 'danger', 7, true, NULL),
  ('Theme', 'LIGHT', 'Light', 'neutral', 1, true, NULL),
  ('Theme', 'DARK', 'Dark', 'neutral', 2, true, NULL),
  ('Theme', 'SYSTEM', 'System posting', 'neutral', 3, true, NULL),
  ('UnitOfMeasureKind', 'COUNT', 'Count', 'neutral', 1, true, NULL),
  ('UnitOfMeasureKind', 'WEIGHT', 'Weight', 'neutral', 2, true, NULL),
  ('UnitOfMeasureKind', 'VOLUME', 'Volume', 'neutral', 3, true, NULL),
  ('UnitOfMeasureKind', 'LENGTH', 'Length', 'neutral', 4, true, NULL),
  ('UserMfaMethod', 'TOTP', 'TOTP', 'neutral', 1, true, NULL),
  ('UserMfaMethod', 'SMS', 'SMS', 'neutral', 2, true, NULL),
  ('UserSessionAuthMethod', 'PASSWORD', 'Password', 'neutral', 1, true, NULL),
  ('UserSessionAuthMethod', 'SSO_GOOGLE', 'SSO google', 'neutral', 2, true, NULL),
  ('UserSessionAuthMethod', 'SSO_MICROSOFT', 'SSO microsoft', 'neutral', 3, true, NULL),
  ('UserSessionAuthMethod', 'SSO_SAML', 'SSO SAML', 'neutral', 4, true, NULL),
  ('UserSsoProvider', 'GOOGLE', 'Google', 'neutral', 1, true, NULL),
  ('UserSsoProvider', 'MICROSOFT', 'Microsoft', 'neutral', 2, true, NULL),
  ('UserStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('UserStatus', 'INVITED', 'Invited', 'warn', 2, true, NULL),
  ('UserStatus', 'SUSPENDED', 'Suspended', 'danger', 3, true, NULL),
  ('UserStatus', 'REMOVED', 'Removed', 'danger', 4, true, NULL),
  ('VendorAtlStatus', 'ACTIVE', 'Active', 'good', 1, true, NULL),
  ('VendorAtlStatus', 'NOT_ON_ATL', 'Not on ATL', 'neutral', 2, true, NULL),
  ('VendorAtlStatus', 'UNVERIFIED', 'Unverified', 'neutral', 3, true, NULL),
  ('VendorBillChannel', 'STANDARD', 'Standard', 'neutral', 1, true, NULL),
  ('VendorBillChannel', 'COUNTER', 'Counter', 'neutral', 2, true, NULL),
  ('VendorBillMatchStatus', 'MATCHED', 'Matched', 'good', 1, true, NULL),
  ('VendorBillMatchStatus', 'QTY_VARIANCE', 'Qty variance', 'warn', 2, true, NULL),
  ('VendorBillMatchStatus', 'PRICE_VARIANCE', 'Price variance', 'warn', 3, true, NULL),
  ('VendorBillMatchStatus', 'NO_PO', 'No PO', 'neutral', 4, true, NULL),
  ('VendorBillPayMode', 'CREDIT', 'Credit', 'neutral', 1, true, NULL),
  ('VendorBillPayMode', 'CASH', 'Cash', 'neutral', 2, true, NULL),
  ('VendorBillPayMode', 'BANK', 'Bank', 'neutral', 3, true, NULL),
  ('VendorBillPayMode', 'CHEQUE', 'Cheque', 'neutral', 4, true, NULL),
  ('VendorBillStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('VendorBillStatus', 'AWAITING_APPROVAL', 'Awaiting approval', 'warn', 2, true, NULL),
  ('VendorBillStatus', 'APPROVED', 'Approved', 'good', 3, true, NULL),
  ('VendorBillStatus', 'POSTED', 'Posted', 'good', 4, true, NULL),
  ('VendorBillStatus', 'PARTIALLY_PAID', 'Partially paid', 'warn', 5, true, NULL),
  ('VendorBillStatus', 'PAID', 'Paid', 'good', 6, true, NULL),
  ('VendorBillStatus', 'VOID', 'Void', 'danger', 7, true, NULL),
  ('VendorPaymentMethod', 'IBFT', 'IBFT', 'neutral', 1, true, NULL),
  ('VendorPaymentMethod', 'CHEQUE', 'Cheque', 'neutral', 2, true, NULL),
  ('VendorPaymentMethod', 'PAY_ORDER', 'PAY order', 'neutral', 3, true, NULL),
  ('VendorPaymentMethod', 'CASH', 'Cash', 'neutral', 4, true, NULL),
  ('VendorPaymentMethod', 'ONLINE', 'Online', 'good', 5, true, NULL),
  ('VendorPaymentStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('VendorPaymentStatus', 'PENDING_APPROVAL', 'Pending approval', 'warn', 2, true, NULL),
  ('VendorPaymentStatus', 'POSTED', 'Posted', 'good', 3, true, NULL),
  ('VendorPaymentStatus', 'PRESENTED', 'Presented', 'info', 4, true, NULL),
  ('VendorPaymentStatus', 'CLEARED', 'Cleared', 'good', 5, true, NULL),
  ('VendorPaymentStatus', 'VOID', 'Void', 'danger', 6, true, NULL),
  ('VoucherInstrumentType', 'CHEQUE', 'Cheque', 'neutral', 1, true, ARRAY['BPV']),
  ('VoucherInstrumentType', 'IBFT', 'IBFT', 'neutral', 2, true, ARRAY['BPV', 'BRV']),
  ('VoucherInstrumentType', 'PAY_ORDER', 'PAY order', 'neutral', 3, true, ARRAY['BPV']),
  ('VoucherInstrumentType', 'RTGS', 'Rtgs', 'neutral', 4, true, ARRAY['BPV']),
  ('VoucherInstrumentType', 'CHEQUE_DEPOSIT', 'Cheque deposit', 'neutral', 5, true, ARRAY['BRV']),
  ('VoucherInstrumentType', 'CASH_DEPOSIT', 'Cash deposit', 'neutral', 6, true, ARRAY['BRV']),
  ('VoucherStatus', 'DRAFT', 'Draft', 'neutral', 1, true, NULL),
  ('VoucherStatus', 'PENDING_APPROVAL', 'Pending approval', 'warn', 2, true, NULL),
  ('VoucherStatus', 'POSTED', 'Posted', 'good', 3, true, NULL),
  ('VoucherStatus', 'REVERSED', 'Reversed', 'danger', 4, true, NULL),
  ('VoucherType', 'JV', 'JV', 'neutral', 1, true, NULL),
  ('VoucherType', 'CPV', 'CPV', 'neutral', 2, true, NULL),
  ('VoucherType', 'CRV', 'CRV', 'neutral', 3, true, NULL),
  ('VoucherType', 'BPV', 'BPV', 'neutral', 4, true, NULL),
  ('VoucherType', 'BRV', 'BRV', 'neutral', 5, true, NULL),
  ('VoucherType', 'CON', 'Contra', 'neutral', 6, true, NULL),
  ('VoucherType', 'OB', 'Opening balance', 'neutral', 7, true, NULL),
  ('VoucherType', 'SYSTEM', 'System posting', 'neutral', 8, true, NULL),
  ('WarehouseType', 'WAREHOUSE', 'Warehouse', 'neutral', 1, true, NULL),
  ('WarehouseType', 'SHOP', 'Shop', 'neutral', 2, true, NULL),
  ('WhtCertificateStatus2', 'NOT_APPLICABLE', 'Not applicable', 'neutral', 1, true, NULL),
  ('WhtCertificateStatus2', 'NOT_YET_RECEIVED', 'Not yet received', 'neutral', 2, true, NULL),
  ('WhtCertificateStatus2', 'RECEIVED', 'Received', 'good', 3, true, NULL),
  ('WhtSection', '153_1_A', '153 1 a', 'neutral', 1, true, NULL),
  ('WhtSection', '153_1_B', '153 1 b', 'neutral', 2, true, NULL),
  ('WhtSection', '153_1_C', '153 1 c', 'neutral', 3, true, NULL),
  ('WhtSection', 'EXEMPT', 'Exempt', 'neutral', 4, true, NULL),
  ('WhtTreatment', 'ALREADY_WITHHELD', 'Already withheld', 'neutral', 1, true, NULL),
  ('WhtTreatment', 'WITHHOLD_NOW', 'Withhold now', 'neutral', 2, true, NULL)
ON CONFLICT DO NOTHING;

INSERT INTO "Lookups"."LookupColumns" ("schemaName", "tableName", "columnName", "lookupType", "allowTenantValues", "dependsOnColumn") VALUES
  ('Platform', 'SubscriptionPlans', 'status', 'SubscriptionPlanStatus', false, NULL),
  ('Platform', 'SubscriptionPlanFeatures', 'moduleKey', 'ModuleKey', false, NULL),
  ('Platform', 'SubscriptionPlanFeatures', 'inclusion', 'Inclusion', false, NULL),
  ('Platform', 'ChartOfAccountsTemplates', 'status', 'ChartOfAccountsTemplateStatus', false, NULL),
  ('Platform', 'ChartOfAccountsTemplateAccounts', 'nature', 'Nature', false, NULL),
  ('Platform', 'Tenants', 'industry', 'TenantIndustry', false, NULL),
  ('Platform', 'Tenants', 'province', 'Province', false, NULL),
  ('Platform', 'Tenants', 'numberFormat', 'NumberFormat', false, NULL),
  ('Platform', 'Tenants', 'dataResidency', 'DataResidency', false, NULL),
  ('Platform', 'Tenants', 'defaultLanguage', 'DefaultLanguage', false, NULL),
  ('Platform', 'Tenants', 'status', 'TenantStatus', false, NULL),
  ('Platform', 'TenantContacts', 'contactRole', 'ContactRole', false, NULL),
  ('Platform', 'TenantContacts', 'language', 'EnUrLanguage', false, NULL),
  ('Platform', 'TenantModules', 'moduleKey', 'ModuleKey', false, NULL),
  ('Platform', 'TenantModules', 'source', 'TenantModuleSource', false, NULL),
  ('Platform', 'Subscriptions', 'billingCycle', 'BillingCycle', false, NULL),
  ('Platform', 'Subscriptions', 'paymentMethod', 'DunningCasePaymentMethod', false, NULL),
  ('Platform', 'Subscriptions', 'status', 'SubscriptionStatus', false, NULL),
  ('Platform', 'PlatformStaff', 'role', 'PlatformStaffMemberRole', false, NULL),
  ('Platform', 'PlatformStaff', 'mfaType', 'MfaType', false, NULL),
  ('Platform', 'PlatformStaff', 'tenantScope', 'TenantScope', false, NULL),
  ('Platform', 'PlatformStaff', 'status', 'PlatformStaffMemberStatus', false, NULL),
  ('Platform', 'PlatformAuditLogs', 'result', 'PlatformAuditLogResult', false, NULL),
  ('Company', 'DocumentTypes', 'module', 'DocumentTypeModule', false, NULL),
  ('Company', 'DocumentTypes', 'defaultResetPolicy', 'DefaultResetPolicy', false, NULL),
  ('Company', 'Permissions', 'module', 'PermissionModule', false, NULL),
  ('Company', 'Permissions', 'action', 'PermissionAction', false, NULL),
  ('Company', 'Branches', 'province', 'Province', false, NULL),
  ('Company', 'Branches', 'salesTaxAuthority', 'SalesTaxAuthority', false, NULL),
  ('Company', 'Branches', 'status', 'ActiveInactiveStatus', false, NULL),
  ('Company', 'Users', 'status', 'UserStatus', false, NULL),
  ('Company', 'Users', 'dataScope', 'DataScope', false, NULL),
  ('Company', 'Users', 'mfaMethod', 'UserMfaMethod', false, NULL),
  ('Company', 'Users', 'loginHours', 'LoginHours', false, NULL),
  ('Company', 'Users', 'ssoProvider', 'UserSsoProvider', false, NULL),
  ('Company', 'Attachments', 'purpose', 'AttachmentPurpose', true, NULL),
  ('Company', 'CompanySettings', 'province', 'Province', false, NULL),
  ('Company', 'CompanySettings', 'industry', 'CompanySettingIndustry', false, NULL),
  ('Company', 'CompanySettings', 'legalStructure', 'LegalStructure', false, NULL),
  ('Company', 'CompanySettings', 'numberFormat', 'NumberFormat', false, NULL),
  ('Company', 'CompanySettings', 'fxRateSource', 'FxRateSource', false, NULL),
  ('Company', 'CompanySettings', 'creditLimitAction', 'CreditLimitAction', false, NULL),
  ('Company', 'CompanySettings', 'salesTaxReturnPeriod', 'SalesTaxReturnPeriod', false, NULL),
  ('Company', 'CompanySettings', 'provincialTaxAuthority', 'ProvincialTaxAuthority', false, NULL),
  ('Company', 'CompanySettings', 'atlStatus', 'CompanySettingAtlStatus', false, NULL),
  ('Company', 'CompanySettings', 'documentFont', 'DocumentFont', false, NULL),
  ('Company', 'CompanySettings', 'paperSize', 'PaperSize', false, NULL),
  ('Company', 'CompanySettingValues', 'settingGroup', 'SettingGroup', false, NULL),
  ('Company', 'PostingRoles', 'roleGroup', 'RoleGroup', false, NULL),
  ('Company', 'PostingRoles', 'normalBalance', 'NormalBalance', false, NULL),
  ('Company', 'Roles', 'systemKey', 'SystemKey', false, NULL),
  ('Company', 'Roles', 'tone', 'RoleTone', false, NULL),
  ('Company', 'UserSessions', 'clientType', 'ClientType', false, NULL),
  ('Company', 'UserSessions', 'authMethod', 'UserSessionAuthMethod', false, NULL),
  ('Company', 'UserSessions', 'revokeReason', 'RevokeReason', true, NULL),
  ('Company', 'PasswordResets', 'purpose', 'PasswordResetPurpose', true, NULL),
  ('Company', 'PasswordResets', 'channel', 'PasswordResetChannel', false, NULL),
  ('Company', 'UserPreferences', 'language', 'EnUrLanguage', false, NULL),
  ('Company', 'UserPreferences', 'dateFormat', 'DateFormat', false, NULL),
  ('Company', 'UserPreferences', 'numberFormat', 'NumberFormat', false, NULL),
  ('Company', 'UserPreferences', 'startRoute', 'StartRoute', false, NULL),
  ('Company', 'UserPreferences', 'theme', 'Theme', false, NULL),
  ('Company', 'NumberingSeries', 'resetPolicy', 'ResetPolicy', false, NULL),
  ('Company', 'Notifications', 'category', 'NotificationCategory', true, NULL),
  ('Company', 'Notifications', 'severity', 'NotificationSeverity', false, NULL),
  ('Company', 'AuditTrailEntries', 'action', 'AuditTrailEntryAction', false, NULL),
  ('Company', 'AuditTrailEntries', 'module', 'AuditTrailEntryModule', false, NULL),
  ('Accounting', 'ChartOfAccounts', 'nature', 'Nature', false, NULL),
  ('Accounting', 'ChartOfAccounts', 'kind', 'AccountKind', false, NULL),
  ('Accounting', 'ChartOfAccounts', 'subType', 'AccountSubType', false, 'accountClass'),
  ('Accounting', 'ChartOfAccounts', 'status', 'ActiveInactiveStatus', false, NULL),
  ('Accounting', 'CostCentres', 'status', 'ActiveInactiveStatus', false, NULL),
  ('Accounting', 'FiscalYears', 'status', 'OpenClosedStatus', false, NULL),
  ('Accounting', 'FiscalPeriods', 'status', 'OpenClosedLockedStatus', false, NULL),
  ('Accounting', 'Vouchers', 'voucherType', 'VoucherType', false, NULL),
  ('Accounting', 'Vouchers', 'instrumentType', 'VoucherInstrumentType', false, 'voucherType'),
  ('Accounting', 'Vouchers', 'status', 'VoucherStatus', false, NULL),
  ('Accounting', 'Vouchers', 'reversalReason', 'ReversalReason', true, NULL),
  ('Accounting', 'OpeningBalances', 'status', 'OpeningBalanceStatus', false, NULL),
  ('BankCash', 'BankAccounts', 'accountType', 'AccountType', false, NULL),
  ('BankCash', 'BankAccounts', 'purpose', 'BankAccountPurpose', true, NULL),
  ('BankCash', 'BankAccounts', 'statementFormat', 'StatementFormat', false, NULL),
  ('BankCash', 'BankAccounts', 'status', 'BankAccountStatus', false, NULL),
  ('BankCash', 'CashAccounts', 'kind', 'CashAccountKind', false, NULL),
  ('BankCash', 'CashCategories', 'direction', 'CashCategoryDirection', false, NULL),
  ('BankCash', 'CashCategories', 'voucherType', 'CashCategoryVoucherType', false, NULL),
  ('BankCash', 'CashCategories', 'partyKind', 'PartyKind', false, NULL),
  ('BankCash', 'Cheques', 'direction', 'ReceivedIssuedDirection', false, NULL),
  ('BankCash', 'Cheques', 'postingMode', 'PostingMode', false, NULL),
  ('BankCash', 'Cheques', 'status', 'ChequeStatus', false, 'direction'),
  ('BankCash', 'ChequeBounces', 'reason', 'ChequeBounceReason', true, NULL),
  ('BankCash', 'ChequeBounces', 'resolution', 'Resolution', false, NULL),
  ('BankCash', 'BankTransactions', 'paymentMode', 'BankTransactionPaymentMode', false, NULL),
  ('BankCash', 'BankTransactions', 'category', 'BankTransactionCategory', true, NULL),
  ('BankCash', 'BankTransactions', 'source', 'BankTransactionSource', false, NULL),
  ('BankCash', 'BankTransactions', 'status', 'BankTransactionStatus', false, NULL),
  ('BankCash', 'CashBookEntries', 'entryKind', 'EntryKind', false, NULL),
  ('BankCash', 'CashBookEntries', 'paymentMode', 'CashBookEntryPaymentMode', false, NULL),
  ('BankCash', 'CashDayCloses', 'status', 'CashDayCloseStatus', false, NULL),
  ('Tax', 'TaxCodes', 'taxType', 'TaxType', false, NULL),
  ('Tax', 'TaxCodes', 'appliesTo', 'TaxCodeAppliesTo', false, NULL),
  ('Tax', 'TaxCodes', 'rateBasis', 'RateBasis', false, NULL),
  ('Tax', 'TaxCodes', 'salesTaxKind', 'SalesTaxKind', false, NULL),
  ('Sales', 'PriceLists', 'status', 'ActiveInactiveStatus', false, NULL),
  ('Sales', 'Customers', 'customerType', 'CustomerType', false, NULL),
  ('Sales', 'Customers', 'atlStatus', 'CustomerAtlStatus', false, NULL),
  ('Sales', 'Customers', 'province', 'Province', false, NULL),
  ('Sales', 'Customers', 'paymentTerms', 'CustomerPaymentTerms', true, NULL),
  ('Sales', 'Customers', 'status', 'CustomerStatus', false, NULL),
  ('Sales', 'Customers', 'holdReason', 'CustomerHoldReason', true, NULL),
  ('Sales', 'Quotations', 'status', 'QuotationStatus', false, NULL),
  ('Sales', 'SalesOrders', 'paymentTerms', 'CustomerPaymentTerms', true, NULL),
  ('Sales', 'SalesOrders', 'status', 'SalesOrderStatus', false, NULL),
  ('Sales', 'SalesInvoices', 'channel', 'SalesInvoiceChannel', false, NULL),
  ('Sales', 'SalesInvoices', 'paymentTerms', 'CustomerPaymentTerms', true, NULL),
  ('Sales', 'SalesInvoices', 'saleType', 'SaleType', false, NULL),
  ('Sales', 'SalesInvoices', 'deliverySlot', 'DeliverySlot', false, NULL),
  ('Sales', 'SalesInvoices', 'status', 'SalesInvoiceStatus', false, NULL),
  ('Sales', 'SalesInvoices', 'fbrStatus', 'FbrStatus', false, NULL),
  ('Sales', 'CreditNotes', 'reason', 'CreditNoteReason', true, NULL),
  ('Sales', 'CreditNotes', 'treatment', 'CreditNoteTreatment', false, NULL),
  ('Sales', 'CreditNotes', 'status', 'CreditNoteStatus', false, NULL),
  ('Sales', 'CustomerReceipts', 'method', 'CustomerReceiptMethod', false, NULL),
  ('Sales', 'CustomerReceipts', 'whtCertificateStatus', 'WhtCertificateStatus2', false, NULL),
  ('Sales', 'CustomerReceipts', 'status', 'CustomerReceiptStatus', false, NULL),
  ('Sales', 'CustomerReceiptAllocations', 'targetType', 'CustomerReceiptAllocationTargetType', false, NULL),
  ('Purchases', 'Vendors', 'atlStatus', 'VendorAtlStatus', false, NULL),
  ('Purchases', 'Vendors', 'defaultWhtSection', 'DefaultWhtSection', false, NULL),
  ('Purchases', 'Vendors', 'paymentTerms', 'PurchaseOrderPaymentTerms', true, NULL),
  ('Purchases', 'Vendors', 'status', 'ActiveInactiveStatus', false, NULL),
  ('Purchases', 'PurchaseOrders', 'paymentTerms', 'PurchaseOrderPaymentTerms', true, NULL),
  ('Purchases', 'PurchaseOrders', 'status', 'PurchaseOrderStatus', false, NULL),
  ('Purchases', 'GoodsReceivedNotes', 'qcStatus', 'QcStatus', false, NULL),
  ('Purchases', 'GoodsReceivedNotes', 'matchStatus', 'GoodsReceivedNoteMatchStatus', false, NULL),
  ('Purchases', 'GoodsReceivedNotes', 'billStatus', 'BillStatus', false, NULL),
  ('Purchases', 'GoodsReceivedNotes', 'status', 'DraftPostedCancelledStatus', false, NULL),
  ('Purchases', 'GoodsReceivedNoteLines', 'rejectReason', 'RejectReason', true, NULL),
  ('Purchases', 'VendorBills', 'channel', 'VendorBillChannel', false, NULL),
  ('Purchases', 'VendorBills', 'captureMethod', 'CaptureMethod', false, NULL),
  ('Purchases', 'VendorBills', 'payMode', 'VendorBillPayMode', false, NULL),
  ('Purchases', 'VendorBills', 'matchStatus', 'VendorBillMatchStatus', false, NULL),
  ('Purchases', 'VendorBills', 'status', 'VendorBillStatus', false, NULL),
  ('Purchases', 'VendorBillLines', 'whtSection', 'WhtSection', false, NULL),
  ('Purchases', 'DebitNotes', 'reason', 'DebitNoteReason', true, NULL),
  ('Purchases', 'DebitNotes', 'settlement', 'DebitNoteSettlement', false, NULL),
  ('Purchases', 'DebitNotes', 'status', 'DebitNoteStatus', false, NULL),
  ('Purchases', 'VendorPayments', 'method', 'VendorPaymentMethod', false, NULL),
  ('Purchases', 'VendorPayments', 'whtTreatment', 'WhtTreatment', false, NULL),
  ('Purchases', 'VendorPayments', 'whtSection', 'WhtSection', false, NULL),
  ('Purchases', 'VendorPayments', 'status', 'VendorPaymentStatus', false, NULL),
  ('Inventory', 'UnitsOfMeasure', 'kind', 'UnitOfMeasureKind', false, NULL),
  ('Inventory', 'ProductCompanies', 'status', 'ActiveInactiveStatus', false, NULL),
  ('Inventory', 'Products', 'status', 'ProductStatus', false, NULL),
  ('Inventory', 'ProductBarcodes', 'kind', 'ProductBarcodeKind', false, NULL),
  ('Inventory', 'Warehouses', 'type', 'WarehouseType', false, NULL),
  ('Inventory', 'Warehouses', 'status', 'ActiveInactiveStatus', false, NULL),
  ('Inventory', 'ProductBatches', 'disposition', 'ProductBatchDisposition', false, NULL),
  ('Inventory', 'StockMovementReasons', 'direction', 'StockMovementReasonDirection', false, NULL),
  ('Inventory', 'StockMovementReasons', 'ledgerMovementType', 'StockMovementReasonLedgerMovementType', false, 'direction'),
  ('Inventory', 'StockMovements', 'movementType', 'MovementType', false, NULL),
  ('Inventory', 'StockInOut', 'mode', 'StockInOutEntryMode', false, NULL),
  ('Inventory', 'StockInOut', 'status', 'DraftPostedCancelledStatus', false, NULL),
  ('Inventory', 'StockTransfers', 'status', 'StockTransferStatus', false, NULL),
  ('Inventory', 'StockAdjustments', 'status', 'StockAdjustmentStatus', false, NULL)
ON CONFLICT DO NOTHING;

-- Attach the validation trigger to every table that has a registered column.
SELECT "Lookups"."attachLookupValidation"();
