import type { PrismaService } from './prisma.service.js';

/**
 * The database's save functions (one per table): insert when `id` is absent, otherwise a partial update.
 * They take the tenant from app.tenantId, check `rowVersion` (40001 when stale) and raise P0002 when not found.
 * Names (and their schema) are allow-listed here because they are interpolated into SQL.
 */
const FUNCTIONS = {
  branchAddUpdate: 'Company',
  exchangeRateAddUpdate: 'Company',
  companySettingAddUpdate: 'Company',
  numberingSeriesAddUpdate: 'Company',
  userAddUpdate: 'Company',
  roleAddUpdate: 'Company',
  userPreferenceAddUpdate: 'Company',
  approvalWorkflowAddUpdate: 'Company',
  approvalDelegationAddUpdate: 'Company',
  documentTemplateAddUpdate: 'Company',
  defaultAccountMappingAddUpdate: 'Company',
  accountAddUpdate: 'Accounting',
  savedLedgerViewAddUpdate: 'Accounting',
  costCentreAddUpdate: 'Accounting',
  projectAddUpdate: 'Accounting',
  costAllocationRuleAddUpdate: 'Accounting',
  taxCodeAddUpdate: 'Tax',
  bankAddUpdate: 'BankCash',
  bankAccountAddUpdate: 'BankCash',
  chequeBookAddUpdate: 'BankCash',
  cashAccountAddUpdate: 'BankCash',
  cashCategoryAddUpdate: 'BankCash',
  expenseCategoryAddUpdate: 'BankCash',
  bankRuleAddUpdate: 'BankCash',
  pettyCashFundAddUpdate: 'BankCash',
  fixedAssetCategoryAddUpdate: 'FixedAssets',
  unitOfMeasureAddUpdate: 'Inventory',
  productCompanyAddUpdate: 'Inventory',
  productClassAddUpdate: 'Inventory',
  productSubclassAddUpdate: 'Inventory',
  warehouseAddUpdate: 'Inventory',
  warehouseBinAddUpdate: 'Inventory',
  stockMovementReasonAddUpdate: 'Inventory',
  productAddUpdate: 'Inventory',
  productUnitAddUpdate: 'Inventory',
  productBarcodeAddUpdate: 'Inventory',
  productSupplierAddUpdate: 'Inventory',
  productPriceLogAdd: 'Inventory',
  productBatchAddUpdate: 'Inventory',
  kitAddUpdate: 'Inventory',
  barcodeLabelTemplateAddUpdate: 'Inventory',
  barcodeLabelJobAddUpdate: 'Inventory',
  reorderRuleAddUpdate: 'Inventory',
  customerGroupAddUpdate: 'Sales',
  customerAddUpdate: 'Sales',
  customerContactAddUpdate: 'Sales',
  customerAddressAddUpdate: 'Sales',
  customerNoteAddUpdate: 'Sales',
  vendorCategoryAddUpdate: 'Purchases',
  vendorAddUpdate: 'Purchases',
  vendorContactAddUpdate: 'Purchases',
  vendorBankAccountAddUpdate: 'Purchases',
  priceListAddUpdate: 'Sales',
  priceListItemsUpsert: 'Sales',
  quantityBreaksReplace: 'Sales',
  salesSchemeAddUpdate: 'Sales',
  paymentReminderTemplateAddUpdate: 'Sales',
  paymentReminderRuleAddUpdate: 'Sales',
  // Phase 23: sales documents
  quotationAddUpdate: 'Sales',
  salesOrderAddUpdate: 'Sales',
  deliveryChallanAddUpdate: 'Sales',
  salesInvoiceAddUpdate: 'Sales',
  // Phase 25: wholesale
  orderTemplateAddUpdate: 'Distribution',
  heldBillAddUpdate: 'Distribution',
  orderBookingAddUpdate: 'Distribution',
  bulkInvoiceRunAddUpdate: 'Distribution',
  // Phase 27: fixed assets
  fixedAssetAddUpdate: 'FixedAssets',
  depreciationRunAddUpdate: 'FixedAssets',
  assetTransferAddUpdate: 'FixedAssets',
  assetDisposalAddUpdate: 'FixedAssets',
  priceTierAddUpdate: 'Distribution',
  departmentAddUpdate: 'HumanResources',
  designationAddUpdate: 'HumanResources',
  gradeAddUpdate: 'HumanResources',
  workShiftAddUpdate: 'HumanResources',
  holidayAddUpdate: 'HumanResources',
  leaveTypeAddUpdate: 'HumanResources',
  leaveEligibilityReplace: 'HumanResources',
  overtimePolicyAddUpdate: 'HumanResources',
  biometricDeviceAddUpdate: 'HumanResources',
  employeeAddUpdate: 'HumanResources',
  branchHrSettingAddUpdate: 'HumanResources',
  salaryComponentAddUpdate: 'Payroll',
  salaryStructureAddUpdate: 'Payroll',
  payGroupAddUpdate: 'Payroll',
  salaryTaxSlabAddUpdate: 'Payroll',
  employeeSalaryAddUpdate: 'Payroll',
  voucherAddUpdate: 'Accounting',
  openingBalanceAddUpdate: 'Accounting',
  recurringVoucherTemplateAddUpdate: 'Accounting',
  approvalAddUpdate: 'Company',
  bankStatementImportAddUpdate: 'BankCash',
  bankReconciliationAddUpdate: 'BankCash',
  chequeAddUpdate: 'BankCash',
  chequeBatchAddUpdate: 'BankCash',
  cashDayCloseAddUpdate: 'BankCash',
  pettyCashVoucherAddUpdate: 'BankCash',
  pettyCashReplenishmentAddUpdate: 'BankCash',
  expenseClaimAddUpdate: 'BankCash',
  purchaseOrderAddUpdate: 'Purchases',
  goodsReceivedNoteAddUpdate: 'Purchases',
  vendorBillAddUpdate: 'Purchases',
  landedCostShipmentAddUpdate: 'Purchases',
  purchaseReturnAddUpdate: 'Purchases',
  debitNoteAddUpdate: 'Purchases',
  vendorPaymentAddUpdate: 'Purchases',
  stockInOutEntryAddUpdate: 'Inventory',
  stockTransferAddUpdate: 'Inventory',
  stockAdjustmentAddUpdate: 'Inventory',
  stockCountAddUpdate: 'Inventory',
  stockVoucherAddUpdate: 'Inventory',
  assemblyVoucherAddUpdate: 'Inventory',
  goodsDemandAddUpdate: 'Inventory',
  principalClaimAddUpdate: 'Inventory',
  principalTargetAddUpdate: 'Inventory',
  bulkPriceUpdateAddUpdate: 'Inventory',
  fbrSettingAddUpdate: 'Tax',
  segregationOfDutiesRuleAddUpdate: 'Company',
  onboardingTemplateAddUpdate: 'HumanResources',
  performanceCycleAddUpdate: 'HumanResources',
  trainingProgramAddUpdate: 'HumanResources',
  companyPolicyAddUpdate: 'EmployeeSelfService',
  shopAreaAddUpdate: 'Distribution',
  routeAddUpdate: 'Distribution',
  shopRouteProfileAddUpdate: 'Distribution',
  vanAddUpdate: 'Distribution',
  commissionSlabAddUpdate: 'Distribution',
  helpdeskCategoryAddUpdate: 'EmployeeSelfService',
  helpdeskFaqAddUpdate: 'EmployeeSelfService',
  companyAnnouncementAddUpdate: 'EmployeeSelfService',
  pollAddUpdate: 'EmployeeSelfService',
  pulseSurveyAddUpdate: 'EmployeeSelfService',
  savedReportAddUpdate: 'Reports',
  reportScheduleAddUpdate: 'Reports',
  // Phase 36: Super Admin catalogue (schema Platform: no tenant; run inside adminActorContext)
  subscriptionPlanAddUpdate: 'Platform',
  platformModuleAddUpdate: 'Platform',
  addonAddUpdate: 'Platform',
  subscriptionCouponAddUpdate: 'Platform',
  // Phase 39: feature flags & alerting (schema Platform; run inside adminActorContext)
  featureFlagAddUpdate: 'Platform',
  flagSdkKeyAddUpdate: 'Platform',
  maintenanceWindowAddUpdate: 'Platform',
  usageAlertRuleAddUpdate: 'Platform',
  auditAlertRuleAddUpdate: 'Platform',
  // Phase 38: platform configuration (schema Platform; run inside adminActorContext; API keys / webhooks with tenantId)
  dunningPolicyAddUpdate: 'Platform',
  tenantSegmentAddUpdate: 'Platform',
  resellerAddUpdate: 'Platform',
  platformSecuritySettingAddUpdate: 'Platform',
  platformAllowedIpAddUpdate: 'Platform',
  platformApiKeyAddUpdate: 'Platform',
  webhookEndpointAddUpdate: 'Platform',
  // Phase 37: seed templates & tax master (schema Platform; run inside adminActorContext)
  chartOfAccountsTemplateAddUpdate: 'Platform',
  templateLeaveTypeAddUpdate: 'Platform',
  templateSalaryComponentAddUpdate: 'Platform',
  templateTaxCodeAddUpdate: 'Platform',
  taxMasterAuthorityAddUpdate: 'Platform',
  taxMasterSalesTaxRateAddUpdate: 'Platform',
  taxMasterWithholdingRateAddUpdate: 'Platform',
  taxMasterSalesTaxRateSchedule: 'Platform',
  taxMasterWithholdingRateSchedule: 'Platform',
  taxMasterSalarySlabAddUpdate: 'Platform',
  communicationTemplateAddUpdate: 'Platform',
  // Phase 30: time & attendance
  regularisationRequestAddUpdate: 'HumanResources',
  overtimeClaimAddUpdate: 'HumanResources',
  shiftRosterEntryAddUpdate: 'HumanResources',
  shiftSwapRequestAddUpdate: 'EmployeeSelfService',
  openShiftAddUpdate: 'EmployeeSelfService',
  // Phase 34: self-service requests
  letterRequestAddUpdate: 'EmployeeSelfService',
  profileChangeRequestAddUpdate: 'EmployeeSelfService',
  helpdeskTicketAddUpdate: 'EmployeeSelfService',
  kudosAddUpdate: 'EmployeeSelfService',
  // Phase 31: leave & lifecycle
  leaveRequestAddUpdate: 'HumanResources',
  leaveAdjustmentAdd: 'HumanResources',
  leaveYearEndClosingAddUpdate: 'HumanResources',
  onboardingFromTemplate: 'HumanResources',
  onboardingAddUpdate: 'HumanResources',
  offboardingAddUpdate: 'HumanResources',
  // Phase 32: payroll
  payrollRunAddUpdate: 'Payroll',
  loanAddUpdate: 'Payroll',
  taxDeclarationAddUpdate: 'Payroll',
  // Phase 42: growth & support (schema Platform; admin writes in adminActorContext, company tickets in actorContext)
  platformLeadAddUpdate: 'Platform',
  leadMoveStage: 'Platform',
  leadConvert: 'Platform',
  supportTicketAddUpdate: 'Platform',
  supportTicketReply: 'Platform',
  announcementAddUpdate: 'Platform',
  tenantBroadcastAddUpdate: 'Platform',
  // Phase 41: platform billing (schema Platform; tenantId from the payload, run inside adminActorContext or the billing job)
  platformInvoiceAddUpdate: 'Platform',
  dunningCaseAddUpdate: 'Platform',
  // Phase 43: platform operations (schema Platform; run inside adminActorContext; the timeline / workflow steps use
  // their own functions: serviceIncidentDeclare / PostUpdate, flagChangeRequestSubmit / Decide, privacyRequest*)
  serviceIncidentAddUpdate: 'Platform',
  privacyRequestAddUpdate: 'Platform',
  // Phase 24: sales completion
  salesReturnAddUpdate: 'Sales',
  creditNoteAddUpdate: 'Sales',
  customerReceiptAddUpdate: 'Sales',
  recurringInvoiceAddUpdate: 'Sales',
  posShiftAddUpdate: 'Sales',
  // Phase 26: distribution
  loadSheetAddUpdate: 'Distribution',
  routeSettlementAddUpdate: 'Distribution',
  recoverySheetAddUpdate: 'Distribution',
  salesmanTargetAddUpdate: 'Distribution',
  salesmanCommissionAddUpdate: 'Distribution',
  creditOverrideAddUpdate: 'Sales',
  // Phase 29: period close
  periodReopenRequestAddUpdate: 'Accounting',
  yearEndCloseAddUpdate: 'Accounting',
  // Phase 28: tax compliance (returns / certificates / statements use their own Tax.* functions)
  whtChallanAddUpdate: 'Tax',
  // Phase 44: work queue & sign-in recovery
  taskAddUpdate: 'Company',
  notificationPreferenceAddUpdate: 'Company',
  userInviteAddUpdate: 'Company',
  // Phase 33 (talent): stage / status moves use their own functions (candidateMove / Hire, performanceReview*, trainingEnrolment*)
  jobOpeningAddUpdate: 'HumanResources',
  candidateAddUpdate: 'HumanResources',
  goalAddUpdate: 'HumanResources',
  performanceFeedbackAddUpdate: 'HumanResources',
  oneOnOneMeetingAddUpdate: 'HumanResources',
  trainingSessionAddUpdate: 'HumanResources',
  trainingEnrolmentAddUpdate: 'HumanResources',
} as const;
export type AddUpdateFunction = keyof typeof FUNCTIONS;

/** Runs <schema>.<fn>(data) on the current withContext transaction and returns the row id. */
export async function addUpdate(prisma: PrismaService, fn: AddUpdateFunction, data: Record<string, unknown>): Promise<string> {
  const schema = FUNCTIONS[fn];
  if (!schema) throw new Error(`Unknown save function ${fn}`);
  const rows = await prisma.db().$queryRawUnsafe<{ id: string }[]>(
    `select "${schema}"."${fn}"($1::jsonb)::text as id`,
    JSON.stringify(data),
  );
  return rows[0]!.id;
}
