import type { PrismaService } from './prisma.service.js';

/** Allow-listed tables (interpolated into SQL as regclass literals). */
const TABLES = {
  taxCodes: '"Tax"."TaxCodes"',
  taxCodeRates: '"Tax"."TaxCodeRates"',
  banks: '"BankCash"."Banks"',
  bankAccounts: '"BankCash"."BankAccounts"',
  chequeBooks: '"BankCash"."ChequeBooks"',
  cashAccounts: '"BankCash"."CashAccounts"',
  cashCategories: '"BankCash"."CashCategories"',
  expenseCategories: '"BankCash"."ExpenseCategories"',
  bankRules: '"BankCash"."BankRules"',
  bankRuleConditions: '"BankCash"."BankRuleConditions"',
  pettyCashFunds: '"BankCash"."PettyCashFunds"',
  fixedAssetCategories: '"FixedAssets"."FixedAssetCategories"',
  unitsOfMeasure: '"Inventory"."UnitsOfMeasure"',
  productCompanies: '"Inventory"."ProductCompanies"',
  productClasses: '"Inventory"."ProductClasses"',
  productSubclasses: '"Inventory"."ProductSubclasses"',
  warehouses: '"Inventory"."Warehouses"',
  warehouseBins: '"Inventory"."WarehouseBins"',
  stockMovementReasons: '"Inventory"."StockMovementReasons"',
  products: '"Inventory"."Products"',
  productUnits: '"Inventory"."ProductUnits"',
  productBarcodes: '"Inventory"."ProductBarcodes"',
  productSuppliers: '"Inventory"."ProductSuppliers"',
  productBatches: '"Inventory"."ProductBatches"',
  productPriceLogs: '"Inventory"."ProductPriceLogs"',
  kits: '"Inventory"."KitsAndBundles"',
  kitComponents: '"Inventory"."KitComponents"',
  labelTemplates: '"Inventory"."BarcodeLabelTemplates"',
  reorderRules: '"Inventory"."ReorderRules"',
  customerGroups: '"Sales"."CustomerGroups"',
  customers: '"Sales"."Customers"',
  customerContacts: '"Sales"."CustomerContacts"',
  customerAddresses: '"Sales"."CustomerAddresses"',
  customerNotes: '"Sales"."CustomerNotes"',
  vendorCategories: '"Purchases"."VendorCategories"',
  vendors: '"Purchases"."Vendors"',
  vendorContacts: '"Purchases"."VendorContacts"',
  vendorBankAccounts: '"Purchases"."VendorBankAccounts"',
  priceLists: '"Sales"."PriceLists"',
  priceListItems: '"Sales"."PriceListItems"',
  quantityBreaks: '"Sales"."PriceListQuantityBreaks"',
  schemes: '"Sales"."SalesSchemes"',
  schemeItems: '"Sales"."SalesSchemeItems"',
  schemeEligibilities: '"Sales"."SalesSchemeEligibilities"',
  reminderTemplates: '"Sales"."PaymentReminderTemplates"',
  reminderRules: '"Sales"."PaymentReminderRules"',
  priceTiers: '"Distribution"."PriceTiers"',
  departments: '"HumanResources"."Departments"',
  designations: '"HumanResources"."Designations"',
  grades: '"HumanResources"."Grades"',
  workShifts: '"HumanResources"."WorkShifts"',
  holidays: '"HumanResources"."Holidays"',
  holidayBranches: '"HumanResources"."HolidayBranches"',
  leaveTypes: '"HumanResources"."LeaveTypes"',
  leaveEligibilityRules: '"HumanResources"."LeaveEligibilityRules"',
  overtimePolicies: '"HumanResources"."OvertimePolicies"',
  devices: '"HumanResources"."BiometricDevices"',
  employees: '"HumanResources"."Employees"',
  employeeStatutory: '"HumanResources"."EmployeeStatutoryDetails"',
  employeeBankAccounts: '"HumanResources"."EmployeeBankAccounts"',
  employeeDocuments: '"HumanResources"."EmployeeDocuments"',
  employeePositionHistory: '"HumanResources"."EmployeePositionHistory"',
  salaryComponents: '"Payroll"."SalaryComponents"',
  salaryStructures: '"Payroll"."SalaryStructures"',
  structureComponents: '"Payroll"."SalaryStructureComponents"',
  commissionTiers: '"Payroll"."SalaryStructureCommissionTiers"',
  payGroups: '"Payroll"."PayGroups"',
  employeeSalaries: '"Payroll"."EmployeeSalaries"',
  vouchers: '"Accounting"."Vouchers"',
  voucherLines: '"Accounting"."VoucherLines"',
  voucherActivities: '"Accounting"."VoucherActivities"',
  recurringTemplates: '"Accounting"."RecurringVoucherTemplates"',
  recurringTemplateLines: '"Accounting"."RecurringVoucherTemplateLines"',
  recurringRuns: '"Accounting"."RecurringVoucherRuns"',
  bankTransactions: '"BankCash"."BankTransactions"',
  statementImports: '"BankCash"."BankStatementImports"',
  statementLines: '"BankCash"."BankStatementLines"',
  reconciliations: '"BankCash"."BankReconciliations"',
  reconciliationMatches: '"BankCash"."BankReconciliationMatches"',
  cheques: '"BankCash"."Cheques"',
  chequeBounces: '"BankCash"."ChequeBounces"',
  chequeBatches: '"BankCash"."ChequeBatches"',
  chequeBatchLines: '"BankCash"."ChequeBatchLines"',
  cashBookEntries: '"BankCash"."CashBookEntries"',
  cashDayCloses: '"BankCash"."CashDayCloses"',
  pettyCashVouchers: '"BankCash"."PettyCashVouchers"',
  pettyCashReplenishments: '"BankCash"."PettyCashReplenishments"',
  expenseClaims: '"BankCash"."ExpenseClaims"',
  expenseClaimLines: '"BankCash"."ExpenseClaimLines"',
  purchaseOrders: '"Purchases"."PurchaseOrders"',
  goodsReceivedNotes: '"Purchases"."GoodsReceivedNotes"',
  vendorBills: '"Purchases"."VendorBills"',
  landedCostShipments: '"Purchases"."LandedCostShipments"',
  purchaseReturns: '"Purchases"."PurchaseReturns"',
  debitNotes: '"Purchases"."DebitNotes"',
  vendorPayments: '"Purchases"."VendorPayments"',
  onboardingTemplates: '"HumanResources"."OnboardingTemplates"',
  onboardingTemplateTasks: '"HumanResources"."OnboardingTemplateTasks"',
  performanceCycles: '"HumanResources"."PerformanceCycles"',
  trainingPrograms: '"HumanResources"."TrainingPrograms"',
  companyPolicies: '"EmployeeSelfService"."CompanyPolicies"',
  shopAreas: '"Distribution"."ShopAreas"',
  routes: '"Distribution"."Routes"',
  routeVisitDays: '"Distribution"."RouteVisitDays"',
  routeStops: '"Distribution"."RouteStops"',
  shopRouteProfiles: '"Distribution"."ShopRouteProfiles"',
  vans: '"Distribution"."Vans"',
  commissionSlabs: '"Distribution"."CommissionSlabs"',
  helpdeskCategories: '"EmployeeSelfService"."HelpdeskCategories"',
  helpdeskFaqs: '"EmployeeSelfService"."HelpdeskFaqs"',
  companyAnnouncements: '"EmployeeSelfService"."CompanyAnnouncements"',
  polls: '"EmployeeSelfService"."Polls"',
  pollOptions: '"EmployeeSelfService"."PollOptions"',
  pulseSurveys: '"EmployeeSelfService"."PulseSurveys"',
  pulseSurveyQuestions: '"EmployeeSelfService"."PulseSurveyQuestions"',
  savedReports: '"Reports"."SavedReports"',
  savedReportColumns: '"Reports"."SavedReportColumns"',
  savedReportShares: '"Reports"."SavedReportShares"',
  reportSchedules: '"Reports"."ReportSchedules"',
  // Phase 36: Super Admin catalogue (schema Platform)
  subscriptionPlans: '"Platform"."SubscriptionPlans"',
  subscriptionPlanFeatures: '"Platform"."SubscriptionPlanFeatures"',
  subscriptionPlanLimits: '"Platform"."SubscriptionPlanLimits"',
  platformModules: '"Platform"."PlatformModules"',
  platformModulePlans: '"Platform"."PlatformModulePlans"',
  addons: '"Platform"."Addons"',
  addonPlans: '"Platform"."AddonPlans"',
  subscriptionCoupons: '"Platform"."SubscriptionCoupons"',
  subscriptionCouponPlans: '"Platform"."SubscriptionCouponPlans"',
  // Phase 39: feature flags & alerting (schema Platform)
  featureFlags: '"Platform"."FeatureFlags"',
  maintenanceWindows: '"Platform"."MaintenanceWindows"',
  usageAlertRules: '"Platform"."UsageAlertRules"',
  auditAlertRules: '"Platform"."AuditAlertRules"',
  // Phase 38: platform configuration (schema Platform)
  dunningPolicies: '"Platform"."DunningPolicies"',
  tenantSegments: '"Platform"."TenantSegments"',
  tenantSegmentRules: '"Platform"."TenantSegmentRules"',
  segmentTenants: '"Platform"."SegmentTenants"',
  resellers: '"Platform"."Resellers"',
  platformAllowedIps: '"Platform"."PlatformAllowedIps"',
  platformApiKeys: '"Platform"."PlatformApiKeys"',
  webhookEndpoints: '"Platform"."WebhookEndpoints"',
  webhookDeliveries: '"Platform"."WebhookDeliveries"',
  backupRuns: '"Platform"."BackupRuns"',
  // Phase 37: seed templates & tax master (schema Platform)
  chartOfAccountsTemplates: '"Platform"."ChartOfAccountsTemplates"',
  chartOfAccountsTemplateAccounts: '"Platform"."ChartOfAccountsTemplateAccounts"',
  templateLeaveTypes: '"Platform"."TemplateLeaveTypes"',
  templateSalaryComponents: '"Platform"."TemplateSalaryComponents"',
  templateTaxCodes: '"Platform"."TemplateTaxCodes"',
  taxMasterSalarySlabs: '"Platform"."TaxMasterSalarySlabs"',
  communicationTemplates: '"Platform"."CommunicationTemplates"',
} as const;
export type ReferencedTable = keyof typeof TABLES;

/** Company.isReferenced: does any row (through a real foreign key) point at this id? `ignore` = the row's own child tables. */
export async function isReferenced(prisma: PrismaService, table: ReferencedTable, id: string, ignore: ReferencedTable[] = []): Promise<boolean> {
  const ignoreSql = ignore.length ? `array[${ignore.map((t) => `'${TABLES[t]}'::regclass`).join(',')}]` : `'{}'::regclass[]`;
  const rows = await prisma.db().$queryRawUnsafe<{ used: boolean }[]>(
    `select "Company"."isReferenced"('${TABLES[table]}'::regclass, $1::uuid, ${ignoreSql}) as used`,
    id,
  );
  return rows[0]!.used;
}

/**
 * Today's balance (debit − credit of posted and reversed vouchers) of GL accounts, keyed by account id. Same sum as
 * BankCash.getBankAccountBalanceOn / getCashAccountBalanceOn, with the tenant passed in (those read app.tenantId,
 * which is only set inside a write transaction).
 */
export async function glBalances(prisma: PrismaService, tenantId: string, accountIds: string[]): Promise<Map<string, number>> {
  if (!accountIds.length) return new Map();
  const rows = await prisma.db().$queryRaw<{ accountId: string; balance: string }[]>`
    select jl."accountId"::text as "accountId", sum(jl.debit - jl.credit)::text as balance
      from "Accounting"."VoucherLines" jl
      join "Accounting"."Vouchers" je on je."tenantId" = jl."tenantId" and je.id = jl."journalEntryId"
     where jl."tenantId" = ${tenantId}::uuid and jl."accountId" = any(${accountIds}::uuid[])
       and je.status in ('POSTED', 'REVERSED') and je."postingDate" <= current_date
     group by jl."accountId"`;
  return new Map(rows.map((r) => [r.accountId, Number(r.balance)]));
}
